// Code generated by MockGen. DO NOT EDIT.
// Source: throttling.go
//
// Generated by this command:
//
//	mockgen -source=throttling.go -destination=throttling_mock.go -package=throttling
//

// Package throttling is a generated GoMock package.
package throttling

import (
	reflect "reflect"

	opera "github.com/0xsoniclabs/sonic/opera"
	idx "github.com/Fantom-foundation/lachesis-base/inter/idx"
	pos "github.com/Fantom-foundation/lachesis-base/inter/pos"
	gomock "go.uber.org/mock/gomock"
)

// MockWorldReader is a mock of WorldReader interface.
type MockWorldReader struct {
	ctrl     *gomock.Controller
	recorder *MockWorldReaderMockRecorder
	isgomock struct{}
}

// MockWorldReaderMockRecorder is the mock recorder for MockWorldReader.
type MockWorldReaderMockRecorder struct {
	mock *MockWorldReader
}

// NewMockWorldReader creates a new mock instance.
func NewMockWorldReader(ctrl *gomock.Controller) *MockWorldReader {
	mock := &MockWorldReader{ctrl: ctrl}
	mock.recorder = &MockWorldReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorldReader) EXPECT() *MockWorldReaderMockRecorder {
	return m.recorder
}

// GetEpochValidators mocks base method.
func (m *MockWorldReader) GetEpochValidators() (*pos.Validators, idx.Epoch) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpochValidators")
	ret0, _ := ret[0].(*pos.Validators)
	ret1, _ := ret[1].(idx.Epoch)
	return ret0, ret1
}

// GetEpochValidators indicates an expected call of GetEpochValidators.
func (mr *MockWorldReaderMockRecorder) GetEpochValidators() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpochValidators", reflect.TypeOf((*MockWorldReader)(nil).GetEpochValidators))
}

// GetLatestBlockIndex mocks base method.
func (m *MockWorldReader) GetLatestBlockIndex() idx.Block {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestBlockIndex")
	ret0, _ := ret[0].(idx.Block)
	return ret0
}

// GetLatestBlockIndex indicates an expected call of GetLatestBlockIndex.
func (mr *MockWorldReaderMockRecorder) GetLatestBlockIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestBlockIndex", reflect.TypeOf((*MockWorldReader)(nil).GetLatestBlockIndex))
}

// GetRules mocks base method.
func (m *MockWorldReader) GetRules() opera.Rules {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRules")
	ret0, _ := ret[0].(opera.Rules)
	return ret0
}

// GetRules indicates an expected call of GetRules.
func (mr *MockWorldReaderMockRecorder) GetRules() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRules", reflect.TypeOf((*MockWorldReader)(nil).GetRules))
}
