// Code generated by MockGen. DO NOT EDIT.
// Source: bundle_api.go
//
// Generated by this command:
//
//	mockgen -source=bundle_api.go -destination=bundle_api_mock.go -package=sonicapi
//

// Package sonicapi is a generated GoMock package.
package sonicapi

import (
	context "context"
	big "math/big"
	reflect "reflect"
	time "time"

	ethapi "github.com/0xsoniclabs/sonic/ethapi"
	evmcore "github.com/0xsoniclabs/sonic/evmcore"
	bundle "github.com/0xsoniclabs/sonic/gossip/blockproc/bundle"
	state "github.com/0xsoniclabs/sonic/inter/state"
	opera "github.com/0xsoniclabs/sonic/opera"
	idx "github.com/Fantom-foundation/lachesis-base/inter/idx"
	common "github.com/ethereum/go-ethereum/common"
	hexutil "github.com/ethereum/go-ethereum/common/hexutil"
	types "github.com/ethereum/go-ethereum/core/types"
	vm "github.com/ethereum/go-ethereum/core/vm"
	params "github.com/ethereum/go-ethereum/params"
	rpc "github.com/ethereum/go-ethereum/rpc"
	gomock "go.uber.org/mock/gomock"
)

// MockBundleApiBackend is a mock of BundleApiBackend interface.
type MockBundleApiBackend struct {
	ctrl     *gomock.Controller
	recorder *MockBundleApiBackendMockRecorder
	isgomock struct{}
}

// MockBundleApiBackendMockRecorder is the mock recorder for MockBundleApiBackend.
type MockBundleApiBackendMockRecorder struct {
	mock *MockBundleApiBackend
}

// NewMockBundleApiBackend creates a new mock instance.
func NewMockBundleApiBackend(ctrl *gomock.Controller) *MockBundleApiBackend {
	mock := &MockBundleApiBackend{ctrl: ctrl}
	mock.recorder = &MockBundleApiBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBundleApiBackend) EXPECT() *MockBundleApiBackendMockRecorder {
	return m.recorder
}

// BlockByHash mocks base method.
func (m *MockBundleApiBackend) BlockByHash(ctx context.Context, hash common.Hash) (*evmcore.EvmBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockByHash", ctx, hash)
	ret0, _ := ret[0].(*evmcore.EvmBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockByHash indicates an expected call of BlockByHash.
func (mr *MockBundleApiBackendMockRecorder) BlockByHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockByHash", reflect.TypeOf((*MockBundleApiBackend)(nil).BlockByHash), ctx, hash)
}

// BlockByNumber mocks base method.
func (m *MockBundleApiBackend) BlockByNumber(ctx context.Context, number rpc.BlockNumber) (*evmcore.EvmBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockByNumber", ctx, number)
	ret0, _ := ret[0].(*evmcore.EvmBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockByNumber indicates an expected call of BlockByNumber.
func (mr *MockBundleApiBackendMockRecorder) BlockByNumber(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockByNumber", reflect.TypeOf((*MockBundleApiBackend)(nil).BlockByNumber), ctx, number)
}

// ChainConfig mocks base method.
func (m *MockBundleApiBackend) ChainConfig(blockHeight idx.Block) *params.ChainConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChainConfig", blockHeight)
	ret0, _ := ret[0].(*params.ChainConfig)
	return ret0
}

// ChainConfig indicates an expected call of ChainConfig.
func (mr *MockBundleApiBackendMockRecorder) ChainConfig(blockHeight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChainConfig", reflect.TypeOf((*MockBundleApiBackend)(nil).ChainConfig), blockHeight)
}

// ChainID mocks base method.
func (m *MockBundleApiBackend) ChainID() *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChainID")
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// ChainID indicates an expected call of ChainID.
func (mr *MockBundleApiBackendMockRecorder) ChainID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChainID", reflect.TypeOf((*MockBundleApiBackend)(nil).ChainID))
}

// CurrentBlock mocks base method.
func (m *MockBundleApiBackend) CurrentBlock() *evmcore.EvmBlock {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentBlock")
	ret0, _ := ret[0].(*evmcore.EvmBlock)
	return ret0
}

// CurrentBlock indicates an expected call of CurrentBlock.
func (mr *MockBundleApiBackendMockRecorder) CurrentBlock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentBlock", reflect.TypeOf((*MockBundleApiBackend)(nil).CurrentBlock))
}

// FetchReceiptsForBlock mocks base method.
func (m *MockBundleApiBackend) FetchReceiptsForBlock(block *evmcore.EvmBlock) types.Receipts {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchReceiptsForBlock", block)
	ret0, _ := ret[0].(types.Receipts)
	return ret0
}

// FetchReceiptsForBlock indicates an expected call of FetchReceiptsForBlock.
func (mr *MockBundleApiBackendMockRecorder) FetchReceiptsForBlock(block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchReceiptsForBlock", reflect.TypeOf((*MockBundleApiBackend)(nil).FetchReceiptsForBlock), block)
}

// GetBundleExecutionInfo mocks base method.
func (m *MockBundleApiBackend) GetBundleExecutionInfo(arg0 common.Hash) *bundle.ExecutionInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBundleExecutionInfo", arg0)
	ret0, _ := ret[0].(*bundle.ExecutionInfo)
	return ret0
}

// GetBundleExecutionInfo indicates an expected call of GetBundleExecutionInfo.
func (mr *MockBundleApiBackendMockRecorder) GetBundleExecutionInfo(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBundleExecutionInfo", reflect.TypeOf((*MockBundleApiBackend)(nil).GetBundleExecutionInfo), arg0)
}

// GetEVM mocks base method.
func (m *MockBundleApiBackend) GetEVM(ctx context.Context, arg1 vm.StateDB, header *evmcore.EvmHeader, vmConfig *vm.Config, blockContext *vm.BlockContext) (*vm.EVM, func() error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEVM", ctx, arg1, header, vmConfig, blockContext)
	ret0, _ := ret[0].(*vm.EVM)
	ret1, _ := ret[1].(func() error)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetEVM indicates an expected call of GetEVM.
func (mr *MockBundleApiBackendMockRecorder) GetEVM(ctx, arg1, header, vmConfig, blockContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEVM", reflect.TypeOf((*MockBundleApiBackend)(nil).GetEVM), ctx, arg1, header, vmConfig, blockContext)
}

// GetGenesisID mocks base method.
func (m *MockBundleApiBackend) GetGenesisID() common.Hash {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGenesisID")
	ret0, _ := ret[0].(common.Hash)
	return ret0
}

// GetGenesisID indicates an expected call of GetGenesisID.
func (mr *MockBundleApiBackendMockRecorder) GetGenesisID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenesisID", reflect.TypeOf((*MockBundleApiBackend)(nil).GetGenesisID))
}

// GetNetworkRules mocks base method.
func (m *MockBundleApiBackend) GetNetworkRules(ctx context.Context, blockHeight idx.Block) (*opera.Rules, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkRules", ctx, blockHeight)
	ret0, _ := ret[0].(*opera.Rules)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkRules indicates an expected call of GetNetworkRules.
func (mr *MockBundleApiBackendMockRecorder) GetNetworkRules(ctx, blockHeight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkRules", reflect.TypeOf((*MockBundleApiBackend)(nil).GetNetworkRules), ctx, blockHeight)
}

// GetReceiptsByNumber mocks base method.
func (m *MockBundleApiBackend) GetReceiptsByNumber(ctx context.Context, number rpc.BlockNumber) (types.Receipts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReceiptsByNumber", ctx, number)
	ret0, _ := ret[0].(types.Receipts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReceiptsByNumber indicates an expected call of GetReceiptsByNumber.
func (mr *MockBundleApiBackendMockRecorder) GetReceiptsByNumber(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceiptsByNumber", reflect.TypeOf((*MockBundleApiBackend)(nil).GetReceiptsByNumber), ctx, number)
}

// GetUpgradeHeights mocks base method.
func (m *MockBundleApiBackend) GetUpgradeHeights() []opera.UpgradeHeight {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpgradeHeights")
	ret0, _ := ret[0].([]opera.UpgradeHeight)
	return ret0
}

// GetUpgradeHeights indicates an expected call of GetUpgradeHeights.
func (mr *MockBundleApiBackendMockRecorder) GetUpgradeHeights() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpgradeHeights", reflect.TypeOf((*MockBundleApiBackend)(nil).GetUpgradeHeights))
}

// HeaderByHash mocks base method.
func (m *MockBundleApiBackend) HeaderByHash(ctx context.Context, hash common.Hash) (*evmcore.EvmHeader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeaderByHash", ctx, hash)
	ret0, _ := ret[0].(*evmcore.EvmHeader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeaderByHash indicates an expected call of HeaderByHash.
func (mr *MockBundleApiBackendMockRecorder) HeaderByHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeaderByHash", reflect.TypeOf((*MockBundleApiBackend)(nil).HeaderByHash), ctx, hash)
}

// HeaderByNumber mocks base method.
func (m *MockBundleApiBackend) HeaderByNumber(ctx context.Context, number rpc.BlockNumber) (*evmcore.EvmHeader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeaderByNumber", ctx, number)
	ret0, _ := ret[0].(*evmcore.EvmHeader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeaderByNumber indicates an expected call of HeaderByNumber.
func (mr *MockBundleApiBackendMockRecorder) HeaderByNumber(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeaderByNumber", reflect.TypeOf((*MockBundleApiBackend)(nil).HeaderByNumber), ctx, number)
}

// MaxGasLimit mocks base method.
func (m *MockBundleApiBackend) MaxGasLimit() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxGasLimit")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// MaxGasLimit indicates an expected call of MaxGasLimit.
func (mr *MockBundleApiBackendMockRecorder) MaxGasLimit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxGasLimit", reflect.TypeOf((*MockBundleApiBackend)(nil).MaxGasLimit))
}

// MinGasPrice mocks base method.
func (m *MockBundleApiBackend) MinGasPrice() *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MinGasPrice")
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// MinGasPrice indicates an expected call of MinGasPrice.
func (mr *MockBundleApiBackendMockRecorder) MinGasPrice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MinGasPrice", reflect.TypeOf((*MockBundleApiBackend)(nil).MinGasPrice))
}

// RPCEVMTimeout mocks base method.
func (m *MockBundleApiBackend) RPCEVMTimeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RPCEVMTimeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// RPCEVMTimeout indicates an expected call of RPCEVMTimeout.
func (mr *MockBundleApiBackendMockRecorder) RPCEVMTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RPCEVMTimeout", reflect.TypeOf((*MockBundleApiBackend)(nil).RPCEVMTimeout))
}

// RPCGasCap mocks base method.
func (m *MockBundleApiBackend) RPCGasCap() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RPCGasCap")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// RPCGasCap indicates an expected call of RPCGasCap.
func (mr *MockBundleApiBackendMockRecorder) RPCGasCap() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RPCGasCap", reflect.TypeOf((*MockBundleApiBackend)(nil).RPCGasCap))
}

// RPCTxFeeCap mocks base method.
func (m *MockBundleApiBackend) RPCTxFeeCap() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RPCTxFeeCap")
	ret0, _ := ret[0].(float64)
	return ret0
}

// RPCTxFeeCap indicates an expected call of RPCTxFeeCap.
func (mr *MockBundleApiBackendMockRecorder) RPCTxFeeCap() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RPCTxFeeCap", reflect.TypeOf((*MockBundleApiBackend)(nil).RPCTxFeeCap))
}

// ResolveRpcBlockNumberOrHash mocks base method.
func (m *MockBundleApiBackend) ResolveRpcBlockNumberOrHash(ctx context.Context, blockNrOrHash rpc.BlockNumberOrHash) (idx.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveRpcBlockNumberOrHash", ctx, blockNrOrHash)
	ret0, _ := ret[0].(idx.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveRpcBlockNumberOrHash indicates an expected call of ResolveRpcBlockNumberOrHash.
func (mr *MockBundleApiBackendMockRecorder) ResolveRpcBlockNumberOrHash(ctx, blockNrOrHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveRpcBlockNumberOrHash", reflect.TypeOf((*MockBundleApiBackend)(nil).ResolveRpcBlockNumberOrHash), ctx, blockNrOrHash)
}

// SendTx mocks base method.
func (m *MockBundleApiBackend) SendTx(ctx context.Context, signedTx *types.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTx", ctx, signedTx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendTx indicates an expected call of SendTx.
func (mr *MockBundleApiBackendMockRecorder) SendTx(ctx, signedTx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTx", reflect.TypeOf((*MockBundleApiBackend)(nil).SendTx), ctx, signedTx)
}

// StateAndBlockByNumberOrHash mocks base method.
func (m *MockBundleApiBackend) StateAndBlockByNumberOrHash(ctx context.Context, blockNrOrHash rpc.BlockNumberOrHash) (state.StateDB, *evmcore.EvmBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StateAndBlockByNumberOrHash", ctx, blockNrOrHash)
	ret0, _ := ret[0].(state.StateDB)
	ret1, _ := ret[1].(*evmcore.EvmBlock)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// StateAndBlockByNumberOrHash indicates an expected call of StateAndBlockByNumberOrHash.
func (mr *MockBundleApiBackendMockRecorder) StateAndBlockByNumberOrHash(ctx, blockNrOrHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StateAndBlockByNumberOrHash", reflect.TypeOf((*MockBundleApiBackend)(nil).StateAndBlockByNumberOrHash), ctx, blockNrOrHash)
}

// UnprotectedAllowed mocks base method.
func (m *MockBundleApiBackend) UnprotectedAllowed() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnprotectedAllowed")
	ret0, _ := ret[0].(bool)
	return ret0
}

// UnprotectedAllowed indicates an expected call of UnprotectedAllowed.
func (mr *MockBundleApiBackendMockRecorder) UnprotectedAllowed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnprotectedAllowed", reflect.TypeOf((*MockBundleApiBackend)(nil).UnprotectedAllowed))
}

// MockGasEstimator is a mock of GasEstimator interface.
type MockGasEstimator struct {
	ctrl     *gomock.Controller
	recorder *MockGasEstimatorMockRecorder
	isgomock struct{}
}

// MockGasEstimatorMockRecorder is the mock recorder for MockGasEstimator.
type MockGasEstimatorMockRecorder struct {
	mock *MockGasEstimator
}

// NewMockGasEstimator creates a new mock instance.
func NewMockGasEstimator(ctrl *gomock.Controller) *MockGasEstimator {
	mock := &MockGasEstimator{ctrl: ctrl}
	mock.recorder = &MockGasEstimatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGasEstimator) EXPECT() *MockGasEstimatorMockRecorder {
	return m.recorder
}

// EstimateGas mocks base method.
func (m *MockGasEstimator) EstimateGas(args ethapi.TransactionArgs, preArgs []ethapi.TransactionArgs) (hexutil.Uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateGas", args, preArgs)
	ret0, _ := ret[0].(hexutil.Uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateGas indicates an expected call of EstimateGas.
func (mr *MockGasEstimatorMockRecorder) EstimateGas(args, preArgs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateGas", reflect.TypeOf((*MockGasEstimator)(nil).EstimateGas), args, preArgs)
}
