// Code generated by MockGen. DO NOT EDIT.
// Source: tx_pool.go
//
// Generated by this command:
//
//	mockgen -source=tx_pool.go -destination=tx_pool_mock.go -package=txpool
//

// Package txpool is a generated GoMock package.
package txpool
