// Code generated by MockGen. DO NOT EDIT.
// Source: sources.go
//
// Generated by this command:
//
//	mockgen -source=sources.go -destination=sources_mock.go -package=networks
//

// Package networks is a generated GoMock package.
package networks

import (
	reflect "reflect"

	peer "github.com/libp2p/go-libp2p/core/peer"
	gomock "go.uber.org/mock/gomock"
)

// MockMembership is a mock of Membership interface.
type MockMembership struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipMockRecorder
	isgomock struct{}
}

// MockMembershipMockRecorder is the mock recorder for MockMembership.
type MockMembershipMockRecorder struct {
	mock *MockMembership
}

// NewMockMembership creates a new mock instance.
func NewMockMembership(ctrl *gomock.Controller) *MockMembership {
	mock := &MockMembership{ctrl: ctrl}
	mock.recorder = &MockMembershipMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMembership) EXPECT() *MockMembershipMockRecorder {
	return m.recorder
}

// Epoch mocks base method.
func (m *MockMembership) Epoch() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Epoch")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Epoch indicates an expected call of Epoch.
func (mr *MockMembershipMockRecorder) Epoch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Epoch", reflect.TypeOf((*MockMembership)(nil).Epoch))
}

// Members mocks base method.
func (m *MockMembership) Members() []Member {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Members")
	ret0, _ := ret[0].([]Member)
	return ret0
}

// Members indicates an expected call of Members.
func (mr *MockMembershipMockRecorder) Members() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Members", reflect.TypeOf((*MockMembership)(nil).Members))
}

// OnChange mocks base method.
func (m *MockMembership) OnChange(callback func()) func() {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnChange", callback)
	ret0, _ := ret[0].(func())
	return ret0
}

// OnChange indicates an expected call of OnChange.
func (mr *MockMembershipMockRecorder) OnChange(callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnChange", reflect.TypeOf((*MockMembership)(nil).OnChange), callback)
}

// MockNodeStatusSource is a mock of NodeStatusSource interface.
type MockNodeStatusSource struct {
	ctrl     *gomock.Controller
	recorder *MockNodeStatusSourceMockRecorder
	isgomock struct{}
}

// MockNodeStatusSourceMockRecorder is the mock recorder for MockNodeStatusSource.
type MockNodeStatusSourceMockRecorder struct {
	mock *MockNodeStatusSource
}

// NewMockNodeStatusSource creates a new mock instance.
func NewMockNodeStatusSource(ctrl *gomock.Controller) *MockNodeStatusSource {
	mock := &MockNodeStatusSource{ctrl: ctrl}
	mock.recorder = &MockNodeStatusSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodeStatusSource) EXPECT() *MockNodeStatusSourceMockRecorder {
	return m.recorder
}

// Status mocks base method.
func (m *MockNodeStatusSource) Status() NodeStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(NodeStatus)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockNodeStatusSourceMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockNodeStatusSource)(nil).Status))
}

// MockPeerSource is a mock of PeerSource interface.
type MockPeerSource struct {
	ctrl     *gomock.Controller
	recorder *MockPeerSourceMockRecorder
	isgomock struct{}
}

// MockPeerSourceMockRecorder is the mock recorder for MockPeerSource.
type MockPeerSourceMockRecorder struct {
	mock *MockPeerSource
}

// NewMockPeerSource creates a new mock instance.
func NewMockPeerSource(ctrl *gomock.Controller) *MockPeerSource {
	mock := &MockPeerSource{ctrl: ctrl}
	mock.recorder = &MockPeerSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPeerSource) EXPECT() *MockPeerSourceMockRecorder {
	return m.recorder
}

// Peers mocks base method.
func (m *MockPeerSource) Peers() []peer.AddrInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Peers")
	ret0, _ := ret[0].([]peer.AddrInfo)
	return ret0
}

// Peers indicates an expected call of Peers.
func (mr *MockPeerSourceMockRecorder) Peers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Peers", reflect.TypeOf((*MockPeerSource)(nil).Peers))
}
