// Code generated by MockGen. DO NOT EDIT.
// Source: sources.go
//
// Generated by this command:
//
//	mockgen -source=sources.go -destination=sources_mock.go -package=networks
//

// Package networks is a generated GoMock package.
package networks

import (
	reflect "reflect"

	peer "github.com/libp2p/go-libp2p/core/peer"
	gomock "go.uber.org/mock/gomock"
)

// MockValidatorSet is a mock of ValidatorSet interface.
type MockValidatorSet struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorSetMockRecorder
	isgomock struct{}
}

// MockValidatorSetMockRecorder is the mock recorder for MockValidatorSet.
type MockValidatorSetMockRecorder struct {
	mock *MockValidatorSet
}

// NewMockValidatorSet creates a new mock instance.
func NewMockValidatorSet(ctrl *gomock.Controller) *MockValidatorSet {
	mock := &MockValidatorSet{ctrl: ctrl}
	mock.recorder = &MockValidatorSetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidatorSet) EXPECT() *MockValidatorSetMockRecorder {
	return m.recorder
}

// Current mocks base method.
func (m *MockValidatorSet) Current() []Validator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Current")
	ret0, _ := ret[0].([]Validator)
	return ret0
}

// Current indicates an expected call of Current.
func (mr *MockValidatorSetMockRecorder) Current() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Current", reflect.TypeOf((*MockValidatorSet)(nil).Current))
}

// Epoch mocks base method.
func (m *MockValidatorSet) Epoch() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Epoch")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Epoch indicates an expected call of Epoch.
func (mr *MockValidatorSetMockRecorder) Epoch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Epoch", reflect.TypeOf((*MockValidatorSet)(nil).Epoch))
}

// OnUpdate mocks base method.
func (m *MockValidatorSet) OnUpdate(callback func([]Validator)) func() {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnUpdate", callback)
	ret0, _ := ret[0].(func())
	return ret0
}

// OnUpdate indicates an expected call of OnUpdate.
func (mr *MockValidatorSetMockRecorder) OnUpdate(callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnUpdate", reflect.TypeOf((*MockValidatorSet)(nil).OnUpdate), callback)
}

// MockNodeStatusSource is a mock of NodeStatusSource interface.
type MockNodeStatusSource struct {
	ctrl     *gomock.Controller
	recorder *MockNodeStatusSourceMockRecorder
	isgomock struct{}
}

// MockNodeStatusSourceMockRecorder is the mock recorder for MockNodeStatusSource.
type MockNodeStatusSourceMockRecorder struct {
	mock *MockNodeStatusSource
}

// NewMockNodeStatusSource creates a new mock instance.
func NewMockNodeStatusSource(ctrl *gomock.Controller) *MockNodeStatusSource {
	mock := &MockNodeStatusSource{ctrl: ctrl}
	mock.recorder = &MockNodeStatusSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodeStatusSource) EXPECT() *MockNodeStatusSourceMockRecorder {
	return m.recorder
}

// Status mocks base method.
func (m *MockNodeStatusSource) Status() NodeStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(NodeStatus)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockNodeStatusSourceMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockNodeStatusSource)(nil).Status))
}

// MockPeerSource is a mock of PeerSource interface.
type MockPeerSource struct {
	ctrl     *gomock.Controller
	recorder *MockPeerSourceMockRecorder
	isgomock struct{}
}

// MockPeerSourceMockRecorder is the mock recorder for MockPeerSource.
type MockPeerSourceMockRecorder struct {
	mock *MockPeerSource
}

// NewMockPeerSource creates a new mock instance.
func NewMockPeerSource(ctrl *gomock.Controller) *MockPeerSource {
	mock := &MockPeerSource{ctrl: ctrl}
	mock.recorder = &MockPeerSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPeerSource) EXPECT() *MockPeerSourceMockRecorder {
	return m.recorder
}

// Peers mocks base method.
func (m *MockPeerSource) Peers() []peer.AddrInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Peers")
	ret0, _ := ret[0].([]peer.AddrInfo)
	return ret0
}

// Peers indicates an expected call of Peers.
func (mr *MockPeerSourceMockRecorder) Peers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Peers", reflect.TypeOf((*MockPeerSource)(nil).Peers))
}
