// Code generated by MockGen. DO NOT EDIT.
// Source: validatordirectory.go
//
// Generated by this command:
//
//	mockgen -source=validatordirectory.go -destination=validatordirectory_mock.go -package=networks
//

// Package networks is a generated GoMock package.
package networks

import (
	reflect "reflect"

	peer "github.com/libp2p/go-libp2p/core/peer"
	multiaddr "github.com/multiformats/go-multiaddr"
	gomock "go.uber.org/mock/gomock"
)

// MockLocalNode is a mock of LocalNode interface.
type MockLocalNode struct {
	ctrl     *gomock.Controller
	recorder *MockLocalNodeMockRecorder
	isgomock struct{}
}

// MockLocalNodeMockRecorder is the mock recorder for MockLocalNode.
type MockLocalNodeMockRecorder struct {
	mock *MockLocalNode
}

// NewMockLocalNode creates a new mock instance.
func NewMockLocalNode(ctrl *gomock.Controller) *MockLocalNode {
	mock := &MockLocalNode{ctrl: ctrl}
	mock.recorder = &MockLocalNodeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocalNode) EXPECT() *MockLocalNodeMockRecorder {
	return m.recorder
}

// Addresses mocks base method.
func (m *MockLocalNode) Addresses() []multiaddr.Multiaddr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Addresses")
	ret0, _ := ret[0].([]multiaddr.Multiaddr)
	return ret0
}

// Addresses indicates an expected call of Addresses.
func (mr *MockLocalNodeMockRecorder) Addresses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Addresses", reflect.TypeOf((*MockLocalNode)(nil).Addresses))
}

// ID mocks base method.
func (m *MockLocalNode) ID() peer.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(peer.ID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockLocalNodeMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockLocalNode)(nil).ID))
}

// MockAddressResolver is a mock of AddressResolver interface.
type MockAddressResolver struct {
	ctrl     *gomock.Controller
	recorder *MockAddressResolverMockRecorder
	isgomock struct{}
}

// MockAddressResolverMockRecorder is the mock recorder for MockAddressResolver.
type MockAddressResolverMockRecorder struct {
	mock *MockAddressResolver
}

// NewMockAddressResolver creates a new mock instance.
func NewMockAddressResolver(ctrl *gomock.Controller) *MockAddressResolver {
	mock := &MockAddressResolver{ctrl: ctrl}
	mock.recorder = &MockAddressResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAddressResolver) EXPECT() *MockAddressResolverMockRecorder {
	return m.recorder
}

// OnDiscovery mocks base method.
func (m *MockAddressResolver) OnDiscovery(callback func()) func() {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnDiscovery", callback)
	ret0, _ := ret[0].(func())
	return ret0
}

// OnDiscovery indicates an expected call of OnDiscovery.
func (mr *MockAddressResolverMockRecorder) OnDiscovery(callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnDiscovery", reflect.TypeOf((*MockAddressResolver)(nil).OnDiscovery), callback)
}

// Resolve mocks base method.
func (m *MockAddressResolver) Resolve(publicKey []byte) (peer.AddrInfo, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", publicKey)
	ret0, _ := ret[0].(peer.AddrInfo)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockAddressResolverMockRecorder) Resolve(publicKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockAddressResolver)(nil).Resolve), publicKey)
}
