// Code generated by MockGen. DO NOT EDIT.
// Source: c_block_callbacks.go
//
// Generated by this command:
//
//	mockgen -source=c_block_callbacks.go -package=gossip -destination=c_block_callbacks_mock.go
//

// Package gossip is a generated GoMock package.
package gossip

import (
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockmetricCounter is a mock of metricCounter interface.
type MockmetricCounter struct {
	ctrl     *gomock.Controller
	recorder *MockmetricCounterMockRecorder
	isgomock struct{}
}

// MockmetricCounterMockRecorder is the mock recorder for MockmetricCounter.
type MockmetricCounterMockRecorder struct {
	mock *MockmetricCounter
}

// NewMockmetricCounter creates a new mock instance.
func NewMockmetricCounter(ctrl *gomock.Controller) *MockmetricCounter {
	mock := &MockmetricCounter{ctrl: ctrl}
	mock.recorder = &MockmetricCounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmetricCounter) EXPECT() *MockmetricCounterMockRecorder {
	return m.recorder
}

// Mark mocks base method.
func (m *MockmetricCounter) Mark(arg0 int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Mark", arg0)
}

// Mark indicates an expected call of Mark.
func (mr *MockmetricCounterMockRecorder) Mark(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mark", reflect.TypeOf((*MockmetricCounter)(nil).Mark), arg0)
}

// MockbundleTracker is a mock of bundleTracker interface.
type MockbundleTracker struct {
	ctrl     *gomock.Controller
	recorder *MockbundleTrackerMockRecorder
	isgomock struct{}
}

// MockbundleTrackerMockRecorder is the mock recorder for MockbundleTracker.
type MockbundleTrackerMockRecorder struct {
	mock *MockbundleTracker
}

// NewMockbundleTracker creates a new mock instance.
func NewMockbundleTracker(ctrl *gomock.Controller) *MockbundleTracker {
	mock := &MockbundleTracker{ctrl: ctrl}
	mock.recorder = &MockbundleTrackerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbundleTracker) EXPECT() *MockbundleTrackerMockRecorder {
	return m.recorder
}

// HasBundleRecentlyBeenProcessed mocks base method.
func (m *MockbundleTracker) HasBundleRecentlyBeenProcessed(execPlanHash common.Hash) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasBundleRecentlyBeenProcessed", execPlanHash)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasBundleRecentlyBeenProcessed indicates an expected call of HasBundleRecentlyBeenProcessed.
func (mr *MockbundleTrackerMockRecorder) HasBundleRecentlyBeenProcessed(execPlanHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasBundleRecentlyBeenProcessed", reflect.TypeOf((*MockbundleTracker)(nil).HasBundleRecentlyBeenProcessed), execPlanHash)
}
