// Code generated by MockGen. DO NOT EDIT.
// Source: emitter_world_test.go
//
// Generated by this command:
//
//	mockgen -source=emitter_world_test.go -destination=emitter_world_mock.go -package=gossip
//

// Package gossip is a generated GoMock package.
package gossip

import (
	reflect "reflect"

	kvdb "github.com/Fantom-foundation/lachesis-base/kvdb"
	gomock "go.uber.org/mock/gomock"
)

// Mock_table is a mock of _table interface.
type Mock_table struct {
	ctrl     *gomock.Controller
	recorder *Mock_tableMockRecorder
	isgomock struct{}
}

// Mock_tableMockRecorder is the mock recorder for Mock_table.
type Mock_tableMockRecorder struct {
	mock *Mock_table
}

// NewMock_table creates a new mock instance.
func NewMock_table(ctrl *gomock.Controller) *Mock_table {
	mock := &Mock_table{ctrl: ctrl}
	mock.recorder = &Mock_tableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mock_table) EXPECT() *Mock_tableMockRecorder {
	return m.recorder
}

// AncientDatadir mocks base method.
func (m *Mock_table) AncientDatadir() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AncientDatadir")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AncientDatadir indicates an expected call of AncientDatadir.
func (mr *Mock_tableMockRecorder) AncientDatadir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AncientDatadir", reflect.TypeOf((*Mock_table)(nil).AncientDatadir))
}

// Close mocks base method.
func (m *Mock_table) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *Mock_tableMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*Mock_table)(nil).Close))
}

// Compact mocks base method.
func (m *Mock_table) Compact(start, limit []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compact", start, limit)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compact indicates an expected call of Compact.
func (mr *Mock_tableMockRecorder) Compact(start, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compact", reflect.TypeOf((*Mock_table)(nil).Compact), start, limit)
}

// Delete mocks base method.
func (m *Mock_table) Delete(key []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *Mock_tableMockRecorder) Delete(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*Mock_table)(nil).Delete), key)
}

// Drop mocks base method.
func (m *Mock_table) Drop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Drop")
}

// Drop indicates an expected call of Drop.
func (mr *Mock_tableMockRecorder) Drop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Drop", reflect.TypeOf((*Mock_table)(nil).Drop))
}

// Get mocks base method.
func (m *Mock_table) Get(key []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *Mock_tableMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*Mock_table)(nil).Get), key)
}

// GetSnapshot mocks base method.
func (m *Mock_table) GetSnapshot() (kvdb.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSnapshot")
	ret0, _ := ret[0].(kvdb.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSnapshot indicates an expected call of GetSnapshot.
func (mr *Mock_tableMockRecorder) GetSnapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSnapshot", reflect.TypeOf((*Mock_table)(nil).GetSnapshot))
}

// Has mocks base method.
func (m *Mock_table) Has(key []byte) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Has", key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Has indicates an expected call of Has.
func (mr *Mock_tableMockRecorder) Has(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Has", reflect.TypeOf((*Mock_table)(nil).Has), key)
}

// NewBatch mocks base method.
func (m *Mock_table) NewBatch() kvdb.Batch {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewBatch")
	ret0, _ := ret[0].(kvdb.Batch)
	return ret0
}

// NewBatch indicates an expected call of NewBatch.
func (mr *Mock_tableMockRecorder) NewBatch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewBatch", reflect.TypeOf((*Mock_table)(nil).NewBatch))
}

// NewIterator mocks base method.
func (m *Mock_table) NewIterator(prefix, start []byte) kvdb.Iterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewIterator", prefix, start)
	ret0, _ := ret[0].(kvdb.Iterator)
	return ret0
}

// NewIterator indicates an expected call of NewIterator.
func (mr *Mock_tableMockRecorder) NewIterator(prefix, start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIterator", reflect.TypeOf((*Mock_table)(nil).NewIterator), prefix, start)
}

// Put mocks base method.
func (m *Mock_table) Put(key, value []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *Mock_tableMockRecorder) Put(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*Mock_table)(nil).Put), key, value)
}

// Stat mocks base method.
func (m *Mock_table) Stat() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *Mock_tableMockRecorder) Stat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*Mock_table)(nil).Stat))
}
