// Code generated by MockGen. DO NOT EDIT.
// Source: evm_state_reader.go
//
// Generated by this command:
//
//	mockgen -source=evm_state_reader.go -destination=evm_state_reader_mock.go -package=gossip
//

// Package gossip is a generated GoMock package.
package gossip

import (
	big "math/big"
	reflect "reflect"

	evmcore "github.com/0xsoniclabs/sonic/evmcore"
	state "github.com/0xsoniclabs/sonic/inter/state"
	opera "github.com/0xsoniclabs/sonic/opera"
	common "github.com/ethereum/go-ethereum/common"
	params "github.com/ethereum/go-ethereum/params"
	gomock "go.uber.org/mock/gomock"
)

// MockStateReader is a mock of StateReader interface.
type MockStateReader struct {
	ctrl     *gomock.Controller
	recorder *MockStateReaderMockRecorder
	isgomock struct{}
}

// MockStateReaderMockRecorder is the mock recorder for MockStateReader.
type MockStateReaderMockRecorder struct {
	mock *MockStateReader
}

// NewMockStateReader creates a new mock instance.
func NewMockStateReader(ctrl *gomock.Controller) *MockStateReader {
	mock := &MockStateReader{ctrl: ctrl}
	mock.recorder = &MockStateReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateReader) EXPECT() *MockStateReaderMockRecorder {
	return m.recorder
}

// Block mocks base method.
func (m *MockStateReader) Block(arg0 common.Hash, arg1 uint64) *evmcore.EvmBlock {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Block", arg0, arg1)
	ret0, _ := ret[0].(*evmcore.EvmBlock)
	return ret0
}

// Block indicates an expected call of Block.
func (mr *MockStateReaderMockRecorder) Block(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Block", reflect.TypeOf((*MockStateReader)(nil).Block), arg0, arg1)
}

// CurrentBaseFee mocks base method.
func (m *MockStateReader) CurrentBaseFee() *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentBaseFee")
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// CurrentBaseFee indicates an expected call of CurrentBaseFee.
func (mr *MockStateReaderMockRecorder) CurrentBaseFee() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentBaseFee", reflect.TypeOf((*MockStateReader)(nil).CurrentBaseFee))
}

// CurrentBlock mocks base method.
func (m *MockStateReader) CurrentBlock() *evmcore.EvmBlock {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentBlock")
	ret0, _ := ret[0].(*evmcore.EvmBlock)
	return ret0
}

// CurrentBlock indicates an expected call of CurrentBlock.
func (mr *MockStateReaderMockRecorder) CurrentBlock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentBlock", reflect.TypeOf((*MockStateReader)(nil).CurrentBlock))
}

// CurrentConfig mocks base method.
func (m *MockStateReader) CurrentConfig() *params.ChainConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentConfig")
	ret0, _ := ret[0].(*params.ChainConfig)
	return ret0
}

// CurrentConfig indicates an expected call of CurrentConfig.
func (mr *MockStateReaderMockRecorder) CurrentConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentConfig", reflect.TypeOf((*MockStateReader)(nil).CurrentConfig))
}

// CurrentHeader mocks base method.
func (m *MockStateReader) CurrentHeader() *evmcore.EvmHeader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentHeader")
	ret0, _ := ret[0].(*evmcore.EvmHeader)
	return ret0
}

// CurrentHeader indicates an expected call of CurrentHeader.
func (mr *MockStateReaderMockRecorder) CurrentHeader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentHeader", reflect.TypeOf((*MockStateReader)(nil).CurrentHeader))
}

// CurrentMaxGasLimit mocks base method.
func (m *MockStateReader) CurrentMaxGasLimit() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentMaxGasLimit")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// CurrentMaxGasLimit indicates an expected call of CurrentMaxGasLimit.
func (mr *MockStateReaderMockRecorder) CurrentMaxGasLimit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentMaxGasLimit", reflect.TypeOf((*MockStateReader)(nil).CurrentMaxGasLimit))
}

// CurrentRules mocks base method.
func (m *MockStateReader) CurrentRules() opera.Rules {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentRules")
	ret0, _ := ret[0].(opera.Rules)
	return ret0
}

// CurrentRules indicates an expected call of CurrentRules.
func (mr *MockStateReaderMockRecorder) CurrentRules() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentRules", reflect.TypeOf((*MockStateReader)(nil).CurrentRules))
}

// GetHeaderByNumber mocks base method.
func (m *MockStateReader) GetHeaderByNumber(n uint64) *evmcore.EvmHeader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeaderByNumber", n)
	ret0, _ := ret[0].(*evmcore.EvmHeader)
	return ret0
}

// GetHeaderByNumber indicates an expected call of GetHeaderByNumber.
func (mr *MockStateReaderMockRecorder) GetHeaderByNumber(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeaderByNumber", reflect.TypeOf((*MockStateReader)(nil).GetHeaderByNumber), n)
}

// Header mocks base method.
func (m *MockStateReader) Header(h common.Hash, n uint64) *evmcore.EvmHeader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header", h, n)
	ret0, _ := ret[0].(*evmcore.EvmHeader)
	return ret0
}

// Header indicates an expected call of Header.
func (mr *MockStateReaderMockRecorder) Header(h, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockStateReader)(nil).Header), h, n)
}

// LastBlockWithArchiveState mocks base method.
func (m *MockStateReader) LastBlockWithArchiveState(withTxs bool) (*evmcore.EvmBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastBlockWithArchiveState", withTxs)
	ret0, _ := ret[0].(*evmcore.EvmBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastBlockWithArchiveState indicates an expected call of LastBlockWithArchiveState.
func (mr *MockStateReaderMockRecorder) LastBlockWithArchiveState(withTxs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastBlockWithArchiveState", reflect.TypeOf((*MockStateReader)(nil).LastBlockWithArchiveState), withTxs)
}

// ReadOnlyStateDB mocks base method.
func (m *MockStateReader) ReadOnlyStateDB() (state.StateDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadOnlyStateDB")
	ret0, _ := ret[0].(state.StateDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadOnlyStateDB indicates an expected call of ReadOnlyStateDB.
func (mr *MockStateReaderMockRecorder) ReadOnlyStateDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadOnlyStateDB", reflect.TypeOf((*MockStateReader)(nil).ReadOnlyStateDB))
}

// RpcStateDB mocks base method.
func (m *MockStateReader) RpcStateDB(arg0 *big.Int, arg1 common.Hash) (state.StateDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RpcStateDB", arg0, arg1)
	ret0, _ := ret[0].(state.StateDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RpcStateDB indicates an expected call of RpcStateDB.
func (mr *MockStateReaderMockRecorder) RpcStateDB(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RpcStateDB", reflect.TypeOf((*MockStateReader)(nil).RpcStateDB), arg0, arg1)
}
