// Code generated by MockGen. DO NOT EDIT.
// Source: gossip/ledger.go
//
// Generated by this command:
//
//	mockgen -source=gossip/ledger.go -destination=gossip/ledger_mock.go -package=gossip
//

// Package gossip is a generated GoMock package.
package gossip

import (
	reflect "reflect"

	evmcore "github.com/0xsoniclabs/sonic/evmcore"
	core_types "github.com/0xsoniclabs/sonic/evmcore/core_types"
	inter "github.com/0xsoniclabs/sonic/inter"
	state "github.com/0xsoniclabs/sonic/inter/state"
	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockLedger is a mock of Ledger interface.
type MockLedger struct {
	ctrl     *gomock.Controller
	recorder *MockLedgerMockRecorder
	isgomock struct{}
}

// MockLedgerMockRecorder is the mock recorder for MockLedger.
type MockLedgerMockRecorder struct {
	mock *MockLedger
}

// NewMockLedger creates a new mock instance.
func NewMockLedger(ctrl *gomock.Controller) *MockLedger {
	mock := &MockLedger{ctrl: ctrl}
	mock.recorder = &MockLedgerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLedger) EXPECT() *MockLedgerMockRecorder {
	return m.recorder
}

// BeginBlock mocks base method.
func (m *MockLedger) BeginBlock(params BlockParams, onNewLog func(*core_types.Log)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginBlock", params, onNewLog)
	ret0, _ := ret[0].(error)
	return ret0
}

// BeginBlock indicates an expected call of BeginBlock.
func (mr *MockLedgerMockRecorder) BeginBlock(params, onNewLog any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginBlock", reflect.TypeOf((*MockLedger)(nil).BeginBlock), params, onNewLog)
}

// Commit mocks base method.
func (m *MockLedger) Commit() (*BlockCandidate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(*BlockCandidate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Commit indicates an expected call of Commit.
func (mr *MockLedgerMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockLedger)(nil).Commit))
}

// Depth mocks base method.
func (m *MockLedger) Depth() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Depth")
	ret0, _ := ret[0].(int)
	return ret0
}

// Depth indicates an expected call of Depth.
func (mr *MockLedgerMockRecorder) Depth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Depth", reflect.TypeOf((*MockLedger)(nil).Depth))
}

// Finalize mocks base method.
func (m *MockLedger) Finalize() *BlockCandidate {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Finalize")
	ret0, _ := ret[0].(*BlockCandidate)
	return ret0
}

// Finalize indicates an expected call of Finalize.
func (mr *MockLedgerMockRecorder) Finalize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finalize", reflect.TypeOf((*MockLedger)(nil).Finalize))
}

// Head mocks base method.
func (m *MockLedger) Head() (*inter.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Head")
	ret0, _ := ret[0].(*inter.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Head indicates an expected call of Head.
func (mr *MockLedgerMockRecorder) Head() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Head", reflect.TypeOf((*MockLedger)(nil).Head))
}

// Publish mocks base method.
func (m *MockLedger) Publish(candidate *BlockCandidate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", candidate)
}

// Publish indicates an expected call of Publish.
func (mr *MockLedgerMockRecorder) Publish(candidate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockLedger)(nil).Publish), candidate)
}

// RevertTo mocks base method.
func (m *MockLedger) RevertTo(keep int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevertTo", keep)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevertTo indicates an expected call of RevertTo.
func (mr *MockLedgerMockRecorder) RevertTo(keep any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevertTo", reflect.TypeOf((*MockLedger)(nil).RevertTo), keep)
}

// Run mocks base method.
func (m *MockLedger) Run(txs types.Transactions) evmcore.ProcessSummary {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", txs)
	ret0, _ := ret[0].(evmcore.ProcessSummary)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockLedgerMockRecorder) Run(txs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockLedger)(nil).Run), txs)
}

// StateDB mocks base method.
func (m *MockLedger) StateDB() state.StateDB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StateDB")
	ret0, _ := ret[0].(state.StateDB)
	return ret0
}

// StateDB indicates an expected call of StateDB.
func (mr *MockLedgerMockRecorder) StateDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StateDB", reflect.TypeOf((*MockLedger)(nil).StateDB))
}

// Tip mocks base method.
func (m *MockLedger) Tip() (*inter.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tip")
	ret0, _ := ret[0].(*inter.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tip indicates an expected call of Tip.
func (mr *MockLedgerMockRecorder) Tip() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tip", reflect.TypeOf((*MockLedger)(nil).Tip))
}

// runInternal mocks base method.
func (m *MockLedger) runInternal(txs types.Transactions) evmcore.ProcessSummary {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "runInternal", txs)
	ret0, _ := ret[0].(evmcore.ProcessSummary)
	return ret0
}

// runInternal indicates an expected call of runInternal.
func (mr *MockLedgerMockRecorder) runInternal(txs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "runInternal", reflect.TypeOf((*MockLedger)(nil).runInternal), txs)
}
