// Code generated by MockGen. DO NOT EDIT.
// Source: ledger.go
//
// Generated by this command:
//
//	mockgen -source=ledger.go -destination=ledger_mock.go -package=gossip
//

// Package gossip is a generated GoMock package.
package gossip

import (
	reflect "reflect"

	evmcore "github.com/0xsoniclabs/sonic/evmcore"
	core_types "github.com/0xsoniclabs/sonic/evmcore/core_types"
	inter "github.com/0xsoniclabs/sonic/inter"
	state "github.com/0xsoniclabs/sonic/inter/state"
	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockLedger is a mock of Ledger interface.
type MockLedger struct {
	ctrl     *gomock.Controller
	recorder *MockLedgerMockRecorder
	isgomock struct{}
}

// MockLedgerMockRecorder is the mock recorder for MockLedger.
type MockLedgerMockRecorder struct {
	mock *MockLedger
}

// NewMockLedger creates a new mock instance.
func NewMockLedger(ctrl *gomock.Controller) *MockLedger {
	mock := &MockLedger{ctrl: ctrl}
	mock.recorder = &MockLedgerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLedger) EXPECT() *MockLedgerMockRecorder {
	return m.recorder
}

// BeginBlock mocks base method.
func (m *MockLedger) BeginBlock(params BlockParams, onNewLog func(*core_types.Log)) (BlockProcessor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginBlock", params, onNewLog)
	ret0, _ := ret[0].(BlockProcessor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginBlock indicates an expected call of BeginBlock.
func (mr *MockLedgerMockRecorder) BeginBlock(params, onNewLog any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginBlock", reflect.TypeOf((*MockLedger)(nil).BeginBlock), params, onNewLog)
}

// GetHeadBlock mocks base method.
func (m *MockLedger) GetHeadBlock() (*inter.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeadBlock")
	ret0, _ := ret[0].(*inter.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeadBlock indicates an expected call of GetHeadBlock.
func (mr *MockLedgerMockRecorder) GetHeadBlock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeadBlock", reflect.TypeOf((*MockLedger)(nil).GetHeadBlock))
}

// MockBlockProcessor is a mock of BlockProcessor interface.
type MockBlockProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockBlockProcessorMockRecorder
	isgomock struct{}
}

// MockBlockProcessorMockRecorder is the mock recorder for MockBlockProcessor.
type MockBlockProcessorMockRecorder struct {
	mock *MockBlockProcessor
}

// NewMockBlockProcessor creates a new mock instance.
func NewMockBlockProcessor(ctrl *gomock.Controller) *MockBlockProcessor {
	mock := &MockBlockProcessor{ctrl: ctrl}
	mock.recorder = &MockBlockProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockProcessor) EXPECT() *MockBlockProcessorMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockBlockProcessor) Commit() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Commit")
}

// Commit indicates an expected call of Commit.
func (mr *MockBlockProcessorMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockBlockProcessor)(nil).Commit))
}

// Finalize mocks base method.
func (m *MockBlockProcessor) Finalize() *BlockCandidate {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Finalize")
	ret0, _ := ret[0].(*BlockCandidate)
	return ret0
}

// Finalize indicates an expected call of Finalize.
func (mr *MockBlockProcessorMockRecorder) Finalize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finalize", reflect.TypeOf((*MockBlockProcessor)(nil).Finalize))
}

// Publish mocks base method.
func (m *MockBlockProcessor) Publish() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish")
}

// Publish indicates an expected call of Publish.
func (mr *MockBlockProcessorMockRecorder) Publish() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockBlockProcessor)(nil).Publish))
}

// Rollback mocks base method.
func (m *MockBlockProcessor) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockBlockProcessorMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockBlockProcessor)(nil).Rollback))
}

// Run mocks base method.
func (m *MockBlockProcessor) Run(txs types.Transactions) evmcore.ProcessSummary {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", txs)
	ret0, _ := ret[0].(evmcore.ProcessSummary)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockBlockProcessorMockRecorder) Run(txs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockBlockProcessor)(nil).Run), txs)
}

// StateDB mocks base method.
func (m *MockBlockProcessor) StateDB() state.StateDB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StateDB")
	ret0, _ := ret[0].(state.StateDB)
	return ret0
}

// StateDB indicates an expected call of StateDB.
func (mr *MockBlockProcessorMockRecorder) StateDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StateDB", reflect.TypeOf((*MockBlockProcessor)(nil).StateDB))
}

// runInternal mocks base method.
func (m *MockBlockProcessor) runInternal(txs types.Transactions) evmcore.ProcessSummary {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "runInternal", txs)
	ret0, _ := ret[0].(evmcore.ProcessSummary)
	return ret0
}

// runInternal indicates an expected call of runInternal.
func (mr *MockBlockProcessorMockRecorder) runInternal(txs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "runInternal", reflect.TypeOf((*MockBlockProcessor)(nil).runInternal), txs)
}
