// Code generated by MockGen. DO NOT EDIT.
// Source: evm_state_reader.go
//
// Generated by this command:
//
//	mockgen -source=evm_state_reader.go -destination=mock_evm_state_reader.go -package=gossip
//

// Package gossip is a generated GoMock package.
package gossip

import (
	big "math/big"
	reflect "reflect"

	evmcore "github.com/0xsoniclabs/sonic/evmcore"
	state "github.com/0xsoniclabs/sonic/inter/state"
	opera "github.com/0xsoniclabs/sonic/opera"
	common "github.com/ethereum/go-ethereum/common"
	params "github.com/ethereum/go-ethereum/params"
	gomock "go.uber.org/mock/gomock"
)

// MockStateReader is a mock of StateReader interface.
type MockStateReader struct {
	ctrl     *gomock.Controller
	recorder *MockStateReaderMockRecorder
	isgomock struct{}
}

// MockStateReaderMockRecorder is the mock recorder for MockStateReader.
type MockStateReaderMockRecorder struct {
	mock *MockStateReader
}

// NewMockStateReader creates a new mock instance.
func NewMockStateReader(ctrl *gomock.Controller) *MockStateReader {
	mock := &MockStateReader{ctrl: ctrl}
	mock.recorder = &MockStateReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateReader) EXPECT() *MockStateReaderMockRecorder {
	return m.recorder
}

// Config mocks base method.
func (m *MockStateReader) Config() *params.ChainConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(*params.ChainConfig)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockStateReaderMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockStateReader)(nil).Config))
}

// CurrentBlock mocks base method.
func (m *MockStateReader) CurrentBlock() *evmcore.EvmBlock {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentBlock")
	ret0, _ := ret[0].(*evmcore.EvmBlock)
	return ret0
}

// CurrentBlock indicates an expected call of CurrentBlock.
func (mr *MockStateReaderMockRecorder) CurrentBlock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentBlock", reflect.TypeOf((*MockStateReader)(nil).CurrentBlock))
}

// CurrentHeader mocks base method.
func (m *MockStateReader) CurrentHeader() *evmcore.EvmHeader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentHeader")
	ret0, _ := ret[0].(*evmcore.EvmHeader)
	return ret0
}

// CurrentHeader indicates an expected call of CurrentHeader.
func (mr *MockStateReaderMockRecorder) CurrentHeader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentHeader", reflect.TypeOf((*MockStateReader)(nil).CurrentHeader))
}

// GetBlock mocks base method.
func (m *MockStateReader) GetBlock(arg0 common.Hash, arg1 uint64) *evmcore.EvmBlock {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlock", arg0, arg1)
	ret0, _ := ret[0].(*evmcore.EvmBlock)
	return ret0
}

// GetBlock indicates an expected call of GetBlock.
func (mr *MockStateReaderMockRecorder) GetBlock(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlock", reflect.TypeOf((*MockStateReader)(nil).GetBlock), arg0, arg1)
}

// GetCurrentBaseFee mocks base method.
func (m *MockStateReader) GetCurrentBaseFee() *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentBaseFee")
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// GetCurrentBaseFee indicates an expected call of GetCurrentBaseFee.
func (mr *MockStateReaderMockRecorder) GetCurrentBaseFee() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentBaseFee", reflect.TypeOf((*MockStateReader)(nil).GetCurrentBaseFee))
}

// GetCurrentRules mocks base method.
func (m *MockStateReader) GetCurrentRules() opera.Rules {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentRules")
	ret0, _ := ret[0].(opera.Rules)
	return ret0
}

// GetCurrentRules indicates an expected call of GetCurrentRules.
func (mr *MockStateReaderMockRecorder) GetCurrentRules() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentRules", reflect.TypeOf((*MockStateReader)(nil).GetCurrentRules))
}

// GetHeader mocks base method.
func (m *MockStateReader) GetHeader(h common.Hash, n uint64) *evmcore.EvmHeader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeader", h, n)
	ret0, _ := ret[0].(*evmcore.EvmHeader)
	return ret0
}

// GetHeader indicates an expected call of GetHeader.
func (mr *MockStateReaderMockRecorder) GetHeader(h, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeader", reflect.TypeOf((*MockStateReader)(nil).GetHeader), h, n)
}

// GetHeaderByNumber mocks base method.
func (m *MockStateReader) GetHeaderByNumber(n uint64) *evmcore.EvmHeader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeaderByNumber", n)
	ret0, _ := ret[0].(*evmcore.EvmHeader)
	return ret0
}

// GetHeaderByNumber indicates an expected call of GetHeaderByNumber.
func (mr *MockStateReaderMockRecorder) GetHeaderByNumber(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeaderByNumber", reflect.TypeOf((*MockStateReader)(nil).GetHeaderByNumber), n)
}

// GetRpcStateDB mocks base method.
func (m *MockStateReader) GetRpcStateDB(arg0 *big.Int, arg1 common.Hash) (state.StateDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRpcStateDB", arg0, arg1)
	ret0, _ := ret[0].(state.StateDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRpcStateDB indicates an expected call of GetRpcStateDB.
func (mr *MockStateReaderMockRecorder) GetRpcStateDB(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRpcStateDB", reflect.TypeOf((*MockStateReader)(nil).GetRpcStateDB), arg0, arg1)
}

// GetTxPoolStateDB mocks base method.
func (m *MockStateReader) GetTxPoolStateDB() (state.StateDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTxPoolStateDB")
	ret0, _ := ret[0].(state.StateDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTxPoolStateDB indicates an expected call of GetTxPoolStateDB.
func (mr *MockStateReaderMockRecorder) GetTxPoolStateDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTxPoolStateDB", reflect.TypeOf((*MockStateReader)(nil).GetTxPoolStateDB))
}

// LastBlockWithArchiveState mocks base method.
func (m *MockStateReader) LastBlockWithArchiveState(withTxs bool) (*evmcore.EvmBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastBlockWithArchiveState", withTxs)
	ret0, _ := ret[0].(*evmcore.EvmBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastBlockWithArchiveState indicates an expected call of LastBlockWithArchiveState.
func (mr *MockStateReaderMockRecorder) LastBlockWithArchiveState(withTxs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastBlockWithArchiveState", reflect.TypeOf((*MockStateReader)(nil).LastBlockWithArchiveState), withTxs)
}

// MaxGasLimit mocks base method.
func (m *MockStateReader) MaxGasLimit() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxGasLimit")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// MaxGasLimit indicates an expected call of MaxGasLimit.
func (mr *MockStateReaderMockRecorder) MaxGasLimit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxGasLimit", reflect.TypeOf((*MockStateReader)(nil).MaxGasLimit))
}
