// Code generated by MockGen. DO NOT EDIT.
// Source: tx_context.go
//
// Generated by this command:
//
//	mockgen -source=tx_context.go -destination=tx_context_mock.go -package=core_types
//

// Package core_types is a generated GoMock package.
package core_types

import (
	reflect "reflect"

	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionRunner is a mock of TransactionRunner interface.
type MockTransactionRunner struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRunnerMockRecorder
	isgomock struct{}
}

// MockTransactionRunnerMockRecorder is the mock recorder for MockTransactionRunner.
type MockTransactionRunnerMockRecorder struct {
	mock *MockTransactionRunner
}

// NewMockTransactionRunner creates a new mock instance.
func NewMockTransactionRunner(ctrl *gomock.Controller) *MockTransactionRunner {
	mock := &MockTransactionRunner{ctrl: ctrl}
	mock.recorder = &MockTransactionRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRunner) EXPECT() *MockTransactionRunnerMockRecorder {
	return m.recorder
}

// RunRegularTransaction mocks base method.
func (m *MockTransactionRunner) RunRegularTransaction(ctxt *RunContext, tx *types.Transaction, txIndex int) (ProcessedTransaction, TransactionResult) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunRegularTransaction", ctxt, tx, txIndex)
	ret0, _ := ret[0].(ProcessedTransaction)
	ret1, _ := ret[1].(TransactionResult)
	return ret0, ret1
}

// RunRegularTransaction indicates an expected call of RunRegularTransaction.
func (mr *MockTransactionRunnerMockRecorder) RunRegularTransaction(ctxt, tx, txIndex any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunRegularTransaction", reflect.TypeOf((*MockTransactionRunner)(nil).RunRegularTransaction), ctxt, tx, txIndex)
}

// RunSponsoredTransaction mocks base method.
func (m *MockTransactionRunner) RunSponsoredTransaction(ctxt *RunContext, tx *types.Transaction, txIndex int) ([]ProcessedTransaction, TransactionResult) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunSponsoredTransaction", ctxt, tx, txIndex)
	ret0, _ := ret[0].([]ProcessedTransaction)
	ret1, _ := ret[1].(TransactionResult)
	return ret0, ret1
}

// RunSponsoredTransaction indicates an expected call of RunSponsoredTransaction.
func (mr *MockTransactionRunnerMockRecorder) RunSponsoredTransaction(ctxt, tx, txIndex any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunSponsoredTransaction", reflect.TypeOf((*MockTransactionRunner)(nil).RunSponsoredTransaction), ctxt, tx, txIndex)
}

// RunTransactionBundle mocks base method.
func (m *MockTransactionRunner) RunTransactionBundle(ctxt *RunContext, tx *types.Transaction, legacyTxIndex, trueTxIndex int) ([]ProcessedTransaction, *ProcessedBundle, TransactionResult) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTransactionBundle", ctxt, tx, legacyTxIndex, trueTxIndex)
	ret0, _ := ret[0].([]ProcessedTransaction)
	ret1, _ := ret[1].(*ProcessedBundle)
	ret2, _ := ret[2].(TransactionResult)
	return ret0, ret1, ret2
}

// RunTransactionBundle indicates an expected call of RunTransactionBundle.
func (mr *MockTransactionRunnerMockRecorder) RunTransactionBundle(ctxt, tx, legacyTxIndex, trueTxIndex any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTransactionBundle", reflect.TypeOf((*MockTransactionRunner)(nil).RunTransactionBundle), ctxt, tx, legacyTxIndex, trueTxIndex)
}
