// Code generated by MockGen. DO NOT EDIT.
// Source: backend.go
//
// Generated by this command:
//
//	mockgen -source=backend.go -destination=backend_mock.go -package=rpctest
//

// Package rpctest is a generated GoMock package.
package rpctest

import (
	reflect "reflect"

	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MocktxPool is a mock of txPool interface.
type MocktxPool struct {
	ctrl     *gomock.Controller
	recorder *MocktxPoolMockRecorder
	isgomock struct{}
}

// MocktxPoolMockRecorder is the mock recorder for MocktxPool.
type MocktxPoolMockRecorder struct {
	mock *MocktxPool
}

// NewMocktxPool creates a new mock instance.
func NewMocktxPool(ctrl *gomock.Controller) *MocktxPool {
	mock := &MocktxPool{ctrl: ctrl}
	mock.recorder = &MocktxPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktxPool) EXPECT() *MocktxPoolMockRecorder {
	return m.recorder
}

// AddLocal mocks base method.
func (m *MocktxPool) AddLocal(arg0 *types.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLocal", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddLocal indicates an expected call of AddLocal.
func (mr *MocktxPoolMockRecorder) AddLocal(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLocal", reflect.TypeOf((*MocktxPool)(nil).AddLocal), arg0)
}
