// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: gossip.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Handshake struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	NetworkId       uint64                 `protobuf:"varint,2,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	Genesis         []byte                 `protobuf:"bytes,3,opt,name=genesis,proto3" json:"genesis,omitempty"` // 32 bytes
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_gossip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{0}
}

func (x *Handshake) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Handshake) GetNetworkId() uint64 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *Handshake) GetGenesis() []byte {
	if x != nil {
		return x.Genesis
	}
	return nil
}

type PeerProgress struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Epoch            uint32                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	LastBlockIdx     uint64                 `protobuf:"varint,2,opt,name=last_block_idx,json=lastBlockIdx,proto3" json:"last_block_idx,omitempty"`
	LastBlockAtropos []byte                 `protobuf:"bytes,3,opt,name=last_block_atropos,json=lastBlockAtropos,proto3" json:"last_block_atropos,omitempty"` // 32 bytes
	HighestLamport   uint32                 `protobuf:"varint,4,opt,name=highest_lamport,json=highestLamport,proto3" json:"highest_lamport,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PeerProgress) Reset() {
	*x = PeerProgress{}
	mi := &file_gossip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerProgress) ProtoMessage() {}

func (x *PeerProgress) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerProgress.ProtoReflect.Descriptor instead.
func (*PeerProgress) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{1}
}

func (x *PeerProgress) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *PeerProgress) GetLastBlockIdx() uint64 {
	if x != nil {
		return x.LastBlockIdx
	}
	return 0
}

func (x *PeerProgress) GetLastBlockAtropos() []byte {
	if x != nil {
		return x.LastBlockAtropos
	}
	return nil
}

func (x *PeerProgress) GetHighestLamport() uint32 {
	if x != nil {
		return x.HighestLamport
	}
	return 0
}

type Transactions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txs           [][]byte               `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"` // Each tx is EIP-2718 encoded bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transactions) Reset() {
	*x = Transactions{}
	mi := &file_gossip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transactions) ProtoMessage() {}

func (x *Transactions) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transactions.ProtoReflect.Descriptor instead.
func (*Transactions) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{2}
}

func (x *Transactions) GetTxs() [][]byte {
	if x != nil {
		return x.Txs
	}
	return nil
}

type Hashes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        [][]byte               `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"` // Each is 32 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hashes) Reset() {
	*x = Hashes{}
	mi := &file_gossip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hashes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hashes) ProtoMessage() {}

func (x *Hashes) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hashes.ProtoReflect.Descriptor instead.
func (*Hashes) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{3}
}

func (x *Hashes) GetHashes() [][]byte {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type EventIDs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           [][]byte               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"` // Each is 32 bytes (hash.Event)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventIDs) Reset() {
	*x = EventIDs{}
	mi := &file_gossip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventIDs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventIDs) ProtoMessage() {}

func (x *EventIDs) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventIDs.ProtoReflect.Descriptor instead.
func (*EventIDs) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{4}
}

func (x *EventIDs) GetIds() [][]byte {
	if x != nil {
		return x.Ids
	}
	return nil
}

type Events struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        [][]byte               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"` // Each event is serialized bytes (stored format)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Events) Reset() {
	*x = Events{}
	mi := &file_gossip_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Events) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Events) ProtoMessage() {}

func (x *Events) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Events.ProtoReflect.Descriptor instead.
func (*Events) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{5}
}

func (x *Events) GetEvents() [][]byte {
	if x != nil {
		return x.Events
	}
	return nil
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     uint32                 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionStart  []byte                 `protobuf:"bytes,2,opt,name=session_start,json=sessionStart,proto3" json:"session_start,omitempty"` // Locator
	SessionStop   []byte                 `protobuf:"bytes,3,opt,name=session_stop,json=sessionStop,proto3" json:"session_stop,omitempty"`    // Locator
	LimitNum      uint64                 `protobuf:"varint,4,opt,name=limit_num,json=limitNum,proto3" json:"limit_num,omitempty"`
	LimitSize     uint64                 `protobuf:"varint,5,opt,name=limit_size,json=limitSize,proto3" json:"limit_size,omitempty"`
	Type          uint32                 `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"` // RequestType
	MaxChunks     uint32                 `protobuf:"varint,7,opt,name=max_chunks,json=maxChunks,proto3" json:"max_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_gossip_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{6}
}

func (x *StreamRequest) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *StreamRequest) GetSessionStart() []byte {
	if x != nil {
		return x.SessionStart
	}
	return nil
}

func (x *StreamRequest) GetSessionStop() []byte {
	if x != nil {
		return x.SessionStop
	}
	return nil
}

func (x *StreamRequest) GetLimitNum() uint64 {
	if x != nil {
		return x.LimitNum
	}
	return 0
}

func (x *StreamRequest) GetLimitSize() uint64 {
	if x != nil {
		return x.LimitSize
	}
	return 0
}

func (x *StreamRequest) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *StreamRequest) GetMaxChunks() uint32 {
	if x != nil {
		return x.MaxChunks
	}
	return 0
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     uint32                 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	Ids           [][]byte               `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`       // Event IDs
	Events        [][]byte               `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"` // Serialized events (stored format)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_gossip_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{7}
}

func (x *StreamResponse) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *StreamResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *StreamResponse) GetIds() [][]byte {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *StreamResponse) GetEvents() [][]byte {
	if x != nil {
		return x.Events
	}
	return nil
}

type PeerInfoEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enode         string                 `protobuf:"bytes,1,opt,name=enode,proto3" json:"enode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfoEntry) Reset() {
	*x = PeerInfoEntry{}
	mi := &file_gossip_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfoEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfoEntry) ProtoMessage() {}

func (x *PeerInfoEntry) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfoEntry.ProtoReflect.Descriptor instead.
func (*PeerInfoEntry) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{8}
}

func (x *PeerInfoEntry) GetEnode() string {
	if x != nil {
		return x.Enode
	}
	return ""
}

type PeerInfos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfoEntry       `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfos) Reset() {
	*x = PeerInfos{}
	mi := &file_gossip_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfos) ProtoMessage() {}

func (x *PeerInfos) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfos.ProtoReflect.Descriptor instead.
func (*PeerInfos) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{9}
}

func (x *PeerInfos) GetPeers() []*PeerInfoEntry {
	if x != nil {
		return x.Peers
	}
	return nil
}

type EndPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enode         string                 `protobuf:"bytes,1,opt,name=enode,proto3" json:"enode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndPoint) Reset() {
	*x = EndPoint{}
	mi := &file_gossip_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndPoint) ProtoMessage() {}

func (x *EndPoint) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndPoint.ProtoReflect.Descriptor instead.
func (*EndPoint) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{10}
}

func (x *EndPoint) GetEnode() string {
	if x != nil {
		return x.Enode
	}
	return ""
}

var File_gossip_proto protoreflect.FileDescriptor

const file_gossip_proto_rawDesc = "" +
	"\n" +
	"\fgossip.proto\x12\x12sonic.gossip.proto\"o\n" +
	"\tHandshake\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"network_id\x18\x02 \x01(\x04R\tnetworkId\x12\x18\n" +
	"\agenesis\x18\x03 \x01(\fR\agenesis\"\xa1\x01\n" +
	"\fPeerProgress\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\rR\x05epoch\x12$\n" +
	"\x0elast_block_idx\x18\x02 \x01(\x04R\flastBlockIdx\x12,\n" +
	"\x12last_block_atropos\x18\x03 \x01(\fR\x10lastBlockAtropos\x12'\n" +
	"\x0fhighest_lamport\x18\x04 \x01(\rR\x0ehighestLamport\" \n" +
	"\fTransactions\x12\x10\n" +
	"\x03txs\x18\x01 \x03(\fR\x03txs\" \n" +
	"\x06Hashes\x12\x16\n" +
	"\x06hashes\x18\x01 \x03(\fR\x06hashes\"\x1c\n" +
	"\bEventIDs\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\fR\x03ids\" \n" +
	"\x06Events\x12\x16\n" +
	"\x06events\x18\x01 \x03(\fR\x06events\"\xe5\x01\n" +
	"\rStreamRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\rR\tsessionId\x12#\n" +
	"\rsession_start\x18\x02 \x01(\fR\fsessionStart\x12!\n" +
	"\fsession_stop\x18\x03 \x01(\fR\vsessionStop\x12\x1b\n" +
	"\tlimit_num\x18\x04 \x01(\x04R\blimitNum\x12\x1d\n" +
	"\n" +
	"limit_size\x18\x05 \x01(\x04R\tlimitSize\x12\x12\n" +
	"\x04type\x18\x06 \x01(\rR\x04type\x12\x1d\n" +
	"\n" +
	"max_chunks\x18\a \x01(\rR\tmaxChunks\"m\n" +
	"\x0eStreamResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\rR\tsessionId\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x10\n" +
	"\x03ids\x18\x03 \x03(\fR\x03ids\x12\x16\n" +
	"\x06events\x18\x04 \x03(\fR\x06events\"%\n" +
	"\rPeerInfoEntry\x12\x14\n" +
	"\x05enode\x18\x01 \x01(\tR\x05enode\"D\n" +
	"\tPeerInfos\x127\n" +
	"\x05peers\x18\x01 \x03(\v2!.sonic.gossip.proto.PeerInfoEntryR\x05peers\" \n" +
	"\bEndPoint\x12\x14\n" +
	"\x05enode\x18\x01 \x01(\tR\x05enodeB\x06Z\x04.;pbb\x06proto3"

var (
	file_gossip_proto_rawDescOnce sync.Once
	file_gossip_proto_rawDescData []byte
)

func file_gossip_proto_rawDescGZIP() []byte {
	file_gossip_proto_rawDescOnce.Do(func() {
		file_gossip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gossip_proto_rawDesc), len(file_gossip_proto_rawDesc)))
	})
	return file_gossip_proto_rawDescData
}

var file_gossip_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_gossip_proto_goTypes = []any{
	(*Handshake)(nil),      // 0: sonic.gossip.proto.Handshake
	(*PeerProgress)(nil),   // 1: sonic.gossip.proto.PeerProgress
	(*Transactions)(nil),   // 2: sonic.gossip.proto.Transactions
	(*Hashes)(nil),         // 3: sonic.gossip.proto.Hashes
	(*EventIDs)(nil),       // 4: sonic.gossip.proto.EventIDs
	(*Events)(nil),         // 5: sonic.gossip.proto.Events
	(*StreamRequest)(nil),  // 6: sonic.gossip.proto.StreamRequest
	(*StreamResponse)(nil), // 7: sonic.gossip.proto.StreamResponse
	(*PeerInfoEntry)(nil),  // 8: sonic.gossip.proto.PeerInfoEntry
	(*PeerInfos)(nil),      // 9: sonic.gossip.proto.PeerInfos
	(*EndPoint)(nil),       // 10: sonic.gossip.proto.EndPoint
}
var file_gossip_proto_depIdxs = []int32{
	8, // 0: sonic.gossip.proto.PeerInfos.peers:type_name -> sonic.gossip.proto.PeerInfoEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gossip_proto_init() }
func file_gossip_proto_init() {
	if File_gossip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gossip_proto_rawDesc), len(file_gossip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gossip_proto_goTypes,
		DependencyIndexes: file_gossip_proto_depIdxs,
		MessageInfos:      file_gossip_proto_msgTypes,
	}.Build()
	File_gossip_proto = out.File
	file_gossip_proto_goTypes = nil
	file_gossip_proto_depIdxs = nil
}
