// Code generated by MockGen. DO NOT EDIT.
// Source: bundle_integration.go
//
// Generated by this command:
//
//	mockgen -source=bundle_integration.go -destination=bundle_integration_mock.go -package=evmcore
//

// Package evmcore is a generated GoMock package.
package evmcore

import (
	reflect "reflect"

	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockbundleChecker is a mock of bundleChecker interface.
type MockbundleChecker struct {
	ctrl     *gomock.Controller
	recorder *MockbundleCheckerMockRecorder
	isgomock struct{}
}

// MockbundleCheckerMockRecorder is the mock recorder for MockbundleChecker.
type MockbundleCheckerMockRecorder struct {
	mock *MockbundleChecker
}

// NewMockbundleChecker creates a new mock instance.
func NewMockbundleChecker(ctrl *gomock.Controller) *MockbundleChecker {
	mock := &MockbundleChecker{ctrl: ctrl}
	mock.recorder = &MockbundleCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbundleChecker) EXPECT() *MockbundleCheckerMockRecorder {
	return m.recorder
}

// isPending mocks base method.
func (m *MockbundleChecker) isPending(tx *types.Transaction) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "isPending", tx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// isPending indicates an expected call of isPending.
func (mr *MockbundleCheckerMockRecorder) isPending(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "isPending", reflect.TypeOf((*MockbundleChecker)(nil).isPending), tx)
}
