// Code generated by MockGen. DO NOT EDIT.
// Source: bundle_precheck.go
//
// Generated by this command:
//
//	mockgen -source=bundle_precheck.go -destination=bundle_precheck_mock.go -package=evmcore
//

// Package evmcore is a generated GoMock package.
package evmcore

import (
	reflect "reflect"

	state "github.com/0xsoniclabs/sonic/inter/state"
	opera "github.com/0xsoniclabs/sonic/opera"
	idx "github.com/Fantom-foundation/lachesis-base/inter/idx"
	common "github.com/ethereum/go-ethereum/common"
	params "github.com/ethereum/go-ethereum/params"
	gomock "go.uber.org/mock/gomock"
)

// MockChainState is a mock of ChainState interface.
type MockChainState struct {
	ctrl     *gomock.Controller
	recorder *MockChainStateMockRecorder
	isgomock struct{}
}

// MockChainStateMockRecorder is the mock recorder for MockChainState.
type MockChainStateMockRecorder struct {
	mock *MockChainState
}

// NewMockChainState creates a new mock instance.
func NewMockChainState(ctrl *gomock.Controller) *MockChainState {
	mock := &MockChainState{ctrl: ctrl}
	mock.recorder = &MockChainStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChainState) EXPECT() *MockChainStateMockRecorder {
	return m.recorder
}

// GetCurrentNetworkRules mocks base method.
func (m *MockChainState) GetCurrentNetworkRules() opera.Rules {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentNetworkRules")
	ret0, _ := ret[0].(opera.Rules)
	return ret0
}

// GetCurrentNetworkRules indicates an expected call of GetCurrentNetworkRules.
func (mr *MockChainStateMockRecorder) GetCurrentNetworkRules() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentNetworkRules", reflect.TypeOf((*MockChainState)(nil).GetCurrentNetworkRules))
}

// GetEvmChainConfig mocks base method.
func (m *MockChainState) GetEvmChainConfig(blockHeight idx.Block) *params.ChainConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvmChainConfig", blockHeight)
	ret0, _ := ret[0].(*params.ChainConfig)
	return ret0
}

// GetEvmChainConfig indicates an expected call of GetEvmChainConfig.
func (mr *MockChainStateMockRecorder) GetEvmChainConfig(blockHeight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvmChainConfig", reflect.TypeOf((*MockChainState)(nil).GetEvmChainConfig), blockHeight)
}

// GetLatestHeader mocks base method.
func (m *MockChainState) GetLatestHeader() *EvmHeader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestHeader")
	ret0, _ := ret[0].(*EvmHeader)
	return ret0
}

// GetLatestHeader indicates an expected call of GetLatestHeader.
func (mr *MockChainStateMockRecorder) GetLatestHeader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestHeader", reflect.TypeOf((*MockChainState)(nil).GetLatestHeader))
}

// Header mocks base method.
func (m *MockChainState) Header(hash common.Hash, number uint64) *EvmHeader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header", hash, number)
	ret0, _ := ret[0].(*EvmHeader)
	return ret0
}

// Header indicates an expected call of Header.
func (mr *MockChainStateMockRecorder) Header(hash, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockChainState)(nil).Header), hash, number)
}

// StateDB mocks base method.
func (m *MockChainState) StateDB() state.StateDB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StateDB")
	ret0, _ := ret[0].(state.StateDB)
	return ret0
}

// StateDB indicates an expected call of StateDB.
func (mr *MockChainStateMockRecorder) StateDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StateDB", reflect.TypeOf((*MockChainState)(nil).StateDB))
}

// MockNonceSource is a mock of NonceSource interface.
type MockNonceSource struct {
	ctrl     *gomock.Controller
	recorder *MockNonceSourceMockRecorder
	isgomock struct{}
}

// MockNonceSourceMockRecorder is the mock recorder for MockNonceSource.
type MockNonceSourceMockRecorder struct {
	mock *MockNonceSource
}

// NewMockNonceSource creates a new mock instance.
func NewMockNonceSource(ctrl *gomock.Controller) *MockNonceSource {
	mock := &MockNonceSource{ctrl: ctrl}
	mock.recorder = &MockNonceSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNonceSource) EXPECT() *MockNonceSourceMockRecorder {
	return m.recorder
}

// GetNonce mocks base method.
func (m *MockNonceSource) GetNonce(addr common.Address) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNonce", addr)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetNonce indicates an expected call of GetNonce.
func (mr *MockNonceSourceMockRecorder) GetNonce(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNonce", reflect.TypeOf((*MockNonceSource)(nil).GetNonce), addr)
}
