// Code generated by MockGen. DO NOT EDIT.
// Source: evm.go
//
// Generated by this command:
//
//	mockgen -source=evm.go -destination=evm_mock.go -package=evmcore
//

// Package evmcore is a generated GoMock package.
package evmcore

import (
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockDummyChain is a mock of DummyChain interface.
type MockDummyChain struct {
	ctrl     *gomock.Controller
	recorder *MockDummyChainMockRecorder
	isgomock struct{}
}

// MockDummyChainMockRecorder is the mock recorder for MockDummyChain.
type MockDummyChainMockRecorder struct {
	mock *MockDummyChain
}

// NewMockDummyChain creates a new mock instance.
func NewMockDummyChain(ctrl *gomock.Controller) *MockDummyChain {
	mock := &MockDummyChain{ctrl: ctrl}
	mock.recorder = &MockDummyChainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDummyChain) EXPECT() *MockDummyChainMockRecorder {
	return m.recorder
}

// Block mocks base method.
func (m *MockDummyChain) Block(hash common.Hash, number uint64) *EvmBlock {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Block", hash, number)
	ret0, _ := ret[0].(*EvmBlock)
	return ret0
}

// Block indicates an expected call of Block.
func (mr *MockDummyChainMockRecorder) Block(hash, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Block", reflect.TypeOf((*MockDummyChain)(nil).Block), hash, number)
}
