// Code generated by MockGen. DO NOT EDIT.
// Source: state_processor.go
//
// Generated by this command:
//
//	mockgen -source=state_processor.go -destination=state_processor_mock.go -package=evmcore
//

// Package evmcore is a generated GoMock package.
package evmcore

import (
	reflect "reflect"

	core_types "github.com/0xsoniclabs/sonic/evmcore/core_types"
	common "github.com/ethereum/go-ethereum/common"
	types "github.com/ethereum/go-ethereum/core/types"
	uint256 "github.com/holiman/uint256"
	gomock "go.uber.org/mock/gomock"
)

// Mock_evm is a mock of _evm interface.
type Mock_evm struct {
	ctrl     *gomock.Controller
	recorder *Mock_evmMockRecorder
	isgomock struct{}
}

// Mock_evmMockRecorder is the mock recorder for Mock_evm.
type Mock_evmMockRecorder struct {
	mock *Mock_evm
}

// NewMock_evm creates a new mock instance.
func NewMock_evm(ctrl *gomock.Controller) *Mock_evm {
	mock := &Mock_evm{ctrl: ctrl}
	mock.recorder = &Mock_evmMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mock_evm) EXPECT() *Mock_evmMockRecorder {
	return m.recorder
}

// Call mocks base method.
func (m *Mock_evm) Call(from, to common.Address, input []byte, gas uint64, value *uint256.Int) ([]byte, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Call", from, to, input, gas, value)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Call indicates an expected call of Call.
func (mr *Mock_evmMockRecorder) Call(from, to, input, gas, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*Mock_evm)(nil).Call), from, to, input, gas, value)
}

// runWithBaseFeeCheck mocks base method.
func (m *Mock_evm) runWithBaseFeeCheck(arg0 *core_types.RunContext, arg1 *types.Transaction, arg2 int) core_types.ProcessedTransaction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "runWithBaseFeeCheck", arg0, arg1, arg2)
	ret0, _ := ret[0].(core_types.ProcessedTransaction)
	return ret0
}

// runWithBaseFeeCheck indicates an expected call of runWithBaseFeeCheck.
func (mr *Mock_evmMockRecorder) runWithBaseFeeCheck(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "runWithBaseFeeCheck", reflect.TypeOf((*Mock_evm)(nil).runWithBaseFeeCheck), arg0, arg1, arg2)
}

// runWithoutBaseFeeCheck mocks base method.
func (m *Mock_evm) runWithoutBaseFeeCheck(arg0 *core_types.RunContext, arg1 *types.Transaction, arg2 int) core_types.ProcessedTransaction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "runWithoutBaseFeeCheck", arg0, arg1, arg2)
	ret0, _ := ret[0].(core_types.ProcessedTransaction)
	return ret0
}

// runWithoutBaseFeeCheck indicates an expected call of runWithoutBaseFeeCheck.
func (mr *Mock_evmMockRecorder) runWithoutBaseFeeCheck(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "runWithoutBaseFeeCheck", reflect.TypeOf((*Mock_evm)(nil).runWithoutBaseFeeCheck), arg0, arg1, arg2)
}
