// Code generated by MockGen. DO NOT EDIT.
// Source: tx_pool.go
//
// Generated by this command:
//
//	mockgen -source=tx_pool.go -destination=tx_pool_mock.go -package=evmcore
//

// Package evmcore is a generated GoMock package.
package evmcore

import (
	big "math/big"
	reflect "reflect"

	opera "github.com/0xsoniclabs/sonic/opera"
	common "github.com/ethereum/go-ethereum/common"
	event "github.com/ethereum/go-ethereum/event"
	params "github.com/ethereum/go-ethereum/params"
	uint256 "github.com/holiman/uint256"
	gomock "go.uber.org/mock/gomock"
)

// MockTxPoolStateDB is a mock of TxPoolStateDB interface.
type MockTxPoolStateDB struct {
	ctrl     *gomock.Controller
	recorder *MockTxPoolStateDBMockRecorder
	isgomock struct{}
}

// MockTxPoolStateDBMockRecorder is the mock recorder for MockTxPoolStateDB.
type MockTxPoolStateDBMockRecorder struct {
	mock *MockTxPoolStateDB
}

// NewMockTxPoolStateDB creates a new mock instance.
func NewMockTxPoolStateDB(ctrl *gomock.Controller) *MockTxPoolStateDB {
	mock := &MockTxPoolStateDB{ctrl: ctrl}
	mock.recorder = &MockTxPoolStateDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxPoolStateDB) EXPECT() *MockTxPoolStateDBMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockTxPoolStateDB) GetBalance(addr common.Address) *uint256.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", addr)
	ret0, _ := ret[0].(*uint256.Int)
	return ret0
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockTxPoolStateDBMockRecorder) GetBalance(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockTxPoolStateDB)(nil).GetBalance), addr)
}

// GetCodeHash mocks base method.
func (m *MockTxPoolStateDB) GetCodeHash(addr common.Address) common.Hash {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCodeHash", addr)
	ret0, _ := ret[0].(common.Hash)
	return ret0
}

// GetCodeHash indicates an expected call of GetCodeHash.
func (mr *MockTxPoolStateDBMockRecorder) GetCodeHash(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCodeHash", reflect.TypeOf((*MockTxPoolStateDB)(nil).GetCodeHash), addr)
}

// GetNonce mocks base method.
func (m *MockTxPoolStateDB) GetNonce(addr common.Address) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNonce", addr)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetNonce indicates an expected call of GetNonce.
func (mr *MockTxPoolStateDBMockRecorder) GetNonce(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNonce", reflect.TypeOf((*MockTxPoolStateDB)(nil).GetNonce), addr)
}

// Release mocks base method.
func (m *MockTxPoolStateDB) Release() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release")
}

// Release indicates an expected call of Release.
func (mr *MockTxPoolStateDBMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockTxPoolStateDB)(nil).Release))
}

// MockStateReader is a mock of StateReader interface.
type MockStateReader struct {
	ctrl     *gomock.Controller
	recorder *MockStateReaderMockRecorder
	isgomock struct{}
}

// MockStateReaderMockRecorder is the mock recorder for MockStateReader.
type MockStateReaderMockRecorder struct {
	mock *MockStateReader
}

// NewMockStateReader creates a new mock instance.
func NewMockStateReader(ctrl *gomock.Controller) *MockStateReader {
	mock := &MockStateReader{ctrl: ctrl}
	mock.recorder = &MockStateReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateReader) EXPECT() *MockStateReaderMockRecorder {
	return m.recorder
}

// Config mocks base method.
func (m *MockStateReader) Config() *params.ChainConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(*params.ChainConfig)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockStateReaderMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockStateReader)(nil).Config))
}

// CurrentBlock mocks base method.
func (m *MockStateReader) CurrentBlock() *EvmBlock {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentBlock")
	ret0, _ := ret[0].(*EvmBlock)
	return ret0
}

// CurrentBlock indicates an expected call of CurrentBlock.
func (mr *MockStateReaderMockRecorder) CurrentBlock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentBlock", reflect.TypeOf((*MockStateReader)(nil).CurrentBlock))
}

// GetBlock mocks base method.
func (m *MockStateReader) GetBlock(hash common.Hash, number uint64) *EvmBlock {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlock", hash, number)
	ret0, _ := ret[0].(*EvmBlock)
	return ret0
}

// GetBlock indicates an expected call of GetBlock.
func (mr *MockStateReaderMockRecorder) GetBlock(hash, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlock", reflect.TypeOf((*MockStateReader)(nil).GetBlock), hash, number)
}

// GetCurrentBaseFee mocks base method.
func (m *MockStateReader) GetCurrentBaseFee() *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentBaseFee")
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// GetCurrentBaseFee indicates an expected call of GetCurrentBaseFee.
func (mr *MockStateReaderMockRecorder) GetCurrentBaseFee() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentBaseFee", reflect.TypeOf((*MockStateReader)(nil).GetCurrentBaseFee))
}

// GetCurrentRules mocks base method.
func (m *MockStateReader) GetCurrentRules() opera.Rules {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentRules")
	ret0, _ := ret[0].(opera.Rules)
	return ret0
}

// GetCurrentRules indicates an expected call of GetCurrentRules.
func (mr *MockStateReaderMockRecorder) GetCurrentRules() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentRules", reflect.TypeOf((*MockStateReader)(nil).GetCurrentRules))
}

// GetTxPoolStateDB mocks base method.
func (m *MockStateReader) GetTxPoolStateDB() (TxPoolStateDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTxPoolStateDB")
	ret0, _ := ret[0].(TxPoolStateDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTxPoolStateDB indicates an expected call of GetTxPoolStateDB.
func (mr *MockStateReaderMockRecorder) GetTxPoolStateDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTxPoolStateDB", reflect.TypeOf((*MockStateReader)(nil).GetTxPoolStateDB))
}

// MaxGasLimit mocks base method.
func (m *MockStateReader) MaxGasLimit() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxGasLimit")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// MaxGasLimit indicates an expected call of MaxGasLimit.
func (mr *MockStateReaderMockRecorder) MaxGasLimit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxGasLimit", reflect.TypeOf((*MockStateReader)(nil).MaxGasLimit))
}

// SubscribeNewBlock mocks base method.
func (m *MockStateReader) SubscribeNewBlock(ch chan<- ChainHeadNotify) event.Subscription {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeNewBlock", ch)
	ret0, _ := ret[0].(event.Subscription)
	return ret0
}

// SubscribeNewBlock indicates an expected call of SubscribeNewBlock.
func (mr *MockStateReaderMockRecorder) SubscribeNewBlock(ch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeNewBlock", reflect.TypeOf((*MockStateReader)(nil).SubscribeNewBlock), ch)
}
