// Code generated by MockGen. DO NOT EDIT.
// Source: bundle_integration.go
//
// Generated by this command:
//
//	mockgen -source=bundle_integration.go -destination=bundle_integration_mock.go -package=corebundles
//

// Package corebundles is a generated GoMock package.
package corebundles

import (
	reflect "reflect"

	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockBundleChecker is a mock of BundleChecker interface.
type MockBundleChecker struct {
	ctrl     *gomock.Controller
	recorder *MockBundleCheckerMockRecorder
	isgomock struct{}
}

// MockBundleCheckerMockRecorder is the mock recorder for MockBundleChecker.
type MockBundleCheckerMockRecorder struct {
	mock *MockBundleChecker
}

// NewMockBundleChecker creates a new mock instance.
func NewMockBundleChecker(ctrl *gomock.Controller) *MockBundleChecker {
	mock := &MockBundleChecker{ctrl: ctrl}
	mock.recorder = &MockBundleCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBundleChecker) EXPECT() *MockBundleCheckerMockRecorder {
	return m.recorder
}

// IsPending mocks base method.
func (m *MockBundleChecker) IsPending(tx *types.Transaction) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPending", tx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsPending indicates an expected call of IsPending.
func (mr *MockBundleCheckerMockRecorder) IsPending(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPending", reflect.TypeOf((*MockBundleChecker)(nil).IsPending), tx)
}
