// Code generated by "stringer -type=BundleStatus -output bundle_status_string.go -trimprefix BundleStatus"; DO NOT EDIT.

package ethapi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BundleStatusUnknown-0]
	_ = x[BundleStatusPending-1]
	_ = x[BundleStatusExecuted-2]
}

const _BundleStatus_name = "UnknownPendingExecuted"

var _BundleStatus_index = [...]uint8{0, 7, 14, 22}

func (i BundleStatus) String() string {
	if i < 0 || i >= BundleStatus(len(_BundleStatus_index)-1) {
		return "BundleStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BundleStatus_name[_BundleStatus_index[i]:_BundleStatus_index[i+1]]
}
