// Code generated by MockGen. DO NOT EDIT.
// Source: contract_calls.go
//
// Generated by this command:
//
//	mockgen -source=contract_calls.go -destination=contract_calls_mock.go -package=priorities
//

// Package priorities is a generated GoMock package.
package priorities

import (
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	uint256 "github.com/holiman/uint256"
	gomock "go.uber.org/mock/gomock"
)

// MockVirtualMachine is a mock of VirtualMachine interface.
type MockVirtualMachine struct {
	ctrl     *gomock.Controller
	recorder *MockVirtualMachineMockRecorder
	isgomock struct{}
}

// MockVirtualMachineMockRecorder is the mock recorder for MockVirtualMachine.
type MockVirtualMachineMockRecorder struct {
	mock *MockVirtualMachine
}

// NewMockVirtualMachine creates a new mock instance.
func NewMockVirtualMachine(ctrl *gomock.Controller) *MockVirtualMachine {
	mock := &MockVirtualMachine{ctrl: ctrl}
	mock.recorder = &MockVirtualMachineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVirtualMachine) EXPECT() *MockVirtualMachineMockRecorder {
	return m.recorder
}

// Call mocks base method.
func (m *MockVirtualMachine) Call(from, to common.Address, input []byte, gas uint64, value *uint256.Int) ([]byte, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Call", from, to, input, gas, value)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Call indicates an expected call of Call.
func (mr *MockVirtualMachineMockRecorder) Call(from, to, input, gas, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockVirtualMachine)(nil).Call), from, to, input, gas, value)
}
