// Code generated by MockGen. DO NOT EDIT.
// Source: ordering.go
//
// Generated by this command:
//
//	mockgen -source=ordering.go -destination=ordering_mock.go -package=priorities
//

// Package priorities is a generated GoMock package.
package priorities

import (
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockClassifier is a mock of Classifier interface.
type MockClassifier struct {
	ctrl     *gomock.Controller
	recorder *MockClassifierMockRecorder
	isgomock struct{}
}

// MockClassifierMockRecorder is the mock recorder for MockClassifier.
type MockClassifierMockRecorder struct {
	mock *MockClassifier
}

// NewMockClassifier creates a new mock instance.
func NewMockClassifier(ctrl *gomock.Controller) *MockClassifier {
	mock := &MockClassifier{ctrl: ctrl}
	mock.recorder = &MockClassifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClassifier) EXPECT() *MockClassifierMockRecorder {
	return m.recorder
}

// Priority mocks base method.
func (m *MockClassifier) Priority(tx *types.Transaction) (Priority, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Priority", tx)
	ret0, _ := ret[0].(Priority)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Priority indicates an expected call of Priority.
func (mr *MockClassifierMockRecorder) Priority(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Priority", reflect.TypeOf((*MockClassifier)(nil).Priority), tx)
}

// MockNonceReader is a mock of NonceReader interface.
type MockNonceReader struct {
	ctrl     *gomock.Controller
	recorder *MockNonceReaderMockRecorder
	isgomock struct{}
}

// MockNonceReaderMockRecorder is the mock recorder for MockNonceReader.
type MockNonceReaderMockRecorder struct {
	mock *MockNonceReader
}

// NewMockNonceReader creates a new mock instance.
func NewMockNonceReader(ctrl *gomock.Controller) *MockNonceReader {
	mock := &MockNonceReader{ctrl: ctrl}
	mock.recorder = &MockNonceReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNonceReader) EXPECT() *MockNonceReaderMockRecorder {
	return m.recorder
}

// GetNonce mocks base method.
func (m *MockNonceReader) GetNonce(arg0 common.Address) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNonce", arg0)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetNonce indicates an expected call of GetNonce.
func (mr *MockNonceReaderMockRecorder) GetNonce(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNonce", reflect.TypeOf((*MockNonceReader)(nil).GetNonce), arg0)
}

// MockSnapshotter is a mock of Snapshotter interface.
type MockSnapshotter struct {
	ctrl     *gomock.Controller
	recorder *MockSnapshotterMockRecorder
	isgomock struct{}
}

// MockSnapshotterMockRecorder is the mock recorder for MockSnapshotter.
type MockSnapshotterMockRecorder struct {
	mock *MockSnapshotter
}

// NewMockSnapshotter creates a new mock instance.
func NewMockSnapshotter(ctrl *gomock.Controller) *MockSnapshotter {
	mock := &MockSnapshotter{ctrl: ctrl}
	mock.recorder = &MockSnapshotterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSnapshotter) EXPECT() *MockSnapshotterMockRecorder {
	return m.recorder
}

// InterTxSnapshot mocks base method.
func (m *MockSnapshotter) InterTxSnapshot() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InterTxSnapshot")
	ret0, _ := ret[0].(int)
	return ret0
}

// InterTxSnapshot indicates an expected call of InterTxSnapshot.
func (mr *MockSnapshotterMockRecorder) InterTxSnapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InterTxSnapshot", reflect.TypeOf((*MockSnapshotter)(nil).InterTxSnapshot))
}

// RevertToInterTxSnapshot mocks base method.
func (m *MockSnapshotter) RevertToInterTxSnapshot(id int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RevertToInterTxSnapshot", id)
}

// RevertToInterTxSnapshot indicates an expected call of RevertToInterTxSnapshot.
func (mr *MockSnapshotterMockRecorder) RevertToInterTxSnapshot(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevertToInterTxSnapshot", reflect.TypeOf((*MockSnapshotter)(nil).RevertToInterTxSnapshot), id)
}
