// Code generated by MockGen. DO NOT EDIT.
// Source: backend.go
//
// Generated by this command:
//
//	mockgen -source=backend.go -destination=backend_mock.go -package=sonicapi
//

// Package sonicapi is a generated GoMock package.
package sonicapi

import (
	reflect "reflect"

	bundle "github.com/0xsoniclabs/sonic/gossip/blockproc/bundle"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// Mockbackend is a mock of backend interface.
type Mockbackend struct {
	ctrl     *gomock.Controller
	recorder *MockbackendMockRecorder
	isgomock struct{}
}

// MockbackendMockRecorder is the mock recorder for Mockbackend.
type MockbackendMockRecorder struct {
	mock *Mockbackend
}

// NewMockbackend creates a new mock instance.
func NewMockbackend(ctrl *gomock.Controller) *Mockbackend {
	mock := &Mockbackend{ctrl: ctrl}
	mock.recorder = &MockbackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockbackend) EXPECT() *MockbackendMockRecorder {
	return m.recorder
}

// GetBundleExecutionInfo mocks base method.
func (m *Mockbackend) GetBundleExecutionInfo(arg0 common.Hash) *bundle.ExecutionInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBundleExecutionInfo", arg0)
	ret0, _ := ret[0].(*bundle.ExecutionInfo)
	return ret0
}

// GetBundleExecutionInfo indicates an expected call of GetBundleExecutionInfo.
func (mr *MockbackendMockRecorder) GetBundleExecutionInfo(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBundleExecutionInfo", reflect.TypeOf((*Mockbackend)(nil).GetBundleExecutionInfo), arg0)
}
