// Code generated by MockGen. DO NOT EDIT.
// Source: bundle_processor.go
//
// Generated by this command:
//
//	mockgen -source=bundle_processor.go -destination=bundle_processor_mock.go -package=bundle
//

// Package bundle is a generated GoMock package.
package bundle

import (
	reflect "reflect"

	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionRunner is a mock of TransactionRunner interface.
type MockTransactionRunner struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRunnerMockRecorder
	isgomock struct{}
}

// MockTransactionRunnerMockRecorder is the mock recorder for MockTransactionRunner.
type MockTransactionRunnerMockRecorder struct {
	mock *MockTransactionRunner
}

// NewMockTransactionRunner creates a new mock instance.
func NewMockTransactionRunner(ctrl *gomock.Controller) *MockTransactionRunner {
	mock := &MockTransactionRunner{ctrl: ctrl}
	mock.recorder = &MockTransactionRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRunner) EXPECT() *MockTransactionRunnerMockRecorder {
	return m.recorder
}

// CreateInterTxSnapshot mocks base method.
func (m *MockTransactionRunner) CreateInterTxSnapshot() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInterTxSnapshot")
	ret0, _ := ret[0].(int)
	return ret0
}

// CreateInterTxSnapshot indicates an expected call of CreateInterTxSnapshot.
func (mr *MockTransactionRunnerMockRecorder) CreateInterTxSnapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInterTxSnapshot", reflect.TypeOf((*MockTransactionRunner)(nil).CreateInterTxSnapshot))
}

// CreateTxSnapshot mocks base method.
func (m *MockTransactionRunner) CreateTxSnapshot() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTxSnapshot")
	ret0, _ := ret[0].(int)
	return ret0
}

// CreateTxSnapshot indicates an expected call of CreateTxSnapshot.
func (mr *MockTransactionRunnerMockRecorder) CreateTxSnapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTxSnapshot", reflect.TypeOf((*MockTransactionRunner)(nil).CreateTxSnapshot))
}

// RevertToInterTxSnapshot mocks base method.
func (m *MockTransactionRunner) RevertToInterTxSnapshot(id int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RevertToInterTxSnapshot", id)
}

// RevertToInterTxSnapshot indicates an expected call of RevertToInterTxSnapshot.
func (mr *MockTransactionRunnerMockRecorder) RevertToInterTxSnapshot(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevertToInterTxSnapshot", reflect.TypeOf((*MockTransactionRunner)(nil).RevertToInterTxSnapshot), id)
}

// RevertToTxSnapshot mocks base method.
func (m *MockTransactionRunner) RevertToTxSnapshot(id int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RevertToTxSnapshot", id)
}

// RevertToTxSnapshot indicates an expected call of RevertToTxSnapshot.
func (mr *MockTransactionRunnerMockRecorder) RevertToTxSnapshot(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevertToTxSnapshot", reflect.TypeOf((*MockTransactionRunner)(nil).RevertToTxSnapshot), id)
}

// Run mocks base method.
func (m *MockTransactionRunner) Run(tx *types.Transaction) TransactionResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", tx)
	ret0, _ := ret[0].(TransactionResult)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockTransactionRunnerMockRecorder) Run(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockTransactionRunner)(nil).Run), tx)
}
