// Code generated by MockGen. DO NOT EDIT.
// Source: bundle_precheck.go
//
// Generated by this command:
//
//	mockgen -source=bundle_precheck.go -destination=bundle_precheck_mock.go -package=bundle
//

// Package bundle is a generated GoMock package.
package bundle

import (
	big "math/big"
	reflect "reflect"

	state "github.com/0xsoniclabs/sonic/inter/state"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockChainState is a mock of ChainState interface.
type MockChainState struct {
	ctrl     *gomock.Controller
	recorder *MockChainStateMockRecorder
	isgomock struct{}
}

// MockChainStateMockRecorder is the mock recorder for MockChainState.
type MockChainStateMockRecorder struct {
	mock *MockChainState
}

// NewMockChainState creates a new mock instance.
func NewMockChainState(ctrl *gomock.Controller) *MockChainState {
	mock := &MockChainState{ctrl: ctrl}
	mock.recorder = &MockChainStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChainState) EXPECT() *MockChainStateMockRecorder {
	return m.recorder
}

// GetChainID mocks base method.
func (m *MockChainState) GetChainID() *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChainID")
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// GetChainID indicates an expected call of GetChainID.
func (mr *MockChainStateMockRecorder) GetChainID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChainID", reflect.TypeOf((*MockChainState)(nil).GetChainID))
}

// GetCurrentBlockHeight mocks base method.
func (m *MockChainState) GetCurrentBlockHeight() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentBlockHeight")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetCurrentBlockHeight indicates an expected call of GetCurrentBlockHeight.
func (mr *MockChainStateMockRecorder) GetCurrentBlockHeight() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentBlockHeight", reflect.TypeOf((*MockChainState)(nil).GetCurrentBlockHeight))
}

// GetStateDB mocks base method.
func (m *MockChainState) GetStateDB() state.StateDB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStateDB")
	ret0, _ := ret[0].(state.StateDB)
	return ret0
}

// GetStateDB indicates an expected call of GetStateDB.
func (mr *MockChainStateMockRecorder) GetStateDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStateDB", reflect.TypeOf((*MockChainState)(nil).GetStateDB))
}

// MockNonceSource is a mock of NonceSource interface.
type MockNonceSource struct {
	ctrl     *gomock.Controller
	recorder *MockNonceSourceMockRecorder
	isgomock struct{}
}

// MockNonceSourceMockRecorder is the mock recorder for MockNonceSource.
type MockNonceSourceMockRecorder struct {
	mock *MockNonceSource
}

// NewMockNonceSource creates a new mock instance.
func NewMockNonceSource(ctrl *gomock.Controller) *MockNonceSource {
	mock := &MockNonceSource{ctrl: ctrl}
	mock.recorder = &MockNonceSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNonceSource) EXPECT() *MockNonceSourceMockRecorder {
	return m.recorder
}

// GetNonce mocks base method.
func (m *MockNonceSource) GetNonce(addr common.Address) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNonce", addr)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetNonce indicates an expected call of GetNonce.
func (mr *MockNonceSourceMockRecorder) GetNonce(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNonce", reflect.TypeOf((*MockNonceSource)(nil).GetNonce), addr)
}
