// Copyright 2026 Sonic Operations Ltd
// This file is part of the Sonic Client
//
// Sonic is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Sonic is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with Sonic. If not, see <http://www.gnu.org/licenses/>.

package bundle

import (
	"crypto/ecdsa"
	"math/big"
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/stretchr/testify/require"
)

var testChainID = big.NewInt(1)

func TestValidate_IdentifiesBundles(t *testing.T) {

	generator := newTestBundleGenerator(t, 2)

	tests := map[string]struct {
		tx           *types.Transaction
		expectBundle bool
	}{
		"not a bundle": {tx: generator.makeNonBundleTx(), expectBundle: false},
		"empty bundle": {tx: generator.makeEmptyBundleTx(), expectBundle: true},
		"valid bundle": {tx: generator.makeValidBundleTx(t), expectBundle: true},
	}

	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			bundle, plan, err := ValidateTransactionBundle(test.tx, generator.signer)
			require.NoError(t, err)
			if test.expectBundle {
				require.NotNil(t, bundle, "expected a bundle transaction")
				require.NotNil(t, plan, "expected an execution plan")
			} else {
				require.Nil(t, bundle, "expected no bundle transaction")
				require.Nil(t, plan, "expected no execution plan")
			}
		})
	}
}

func TestValidate_ReturnsErrorsOnValidationFailure(t *testing.T) {

	generator := newTestBundleGenerator(t, 2)

	tests := map[string]struct {
		tx            *types.Transaction
		expectedError string
	}{
		"invalid bundle": {
			tx:            generator.makeWrongVersionBundleTx(),
			expectedError: "unsupported bundle version",
		},
		"unsound bundle": {
			tx:            generator.makeUnsoundBundleTx(t),
			expectedError: "does not belong to the execution plan",
		},
		"wrongly signed bundle": {
			tx:            generator.makeBundleTxWithWronglySignedTx(t),
			expectedError: "failed to derive sender",
		},
	}

	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			_, _, err := ValidateTransactionBundle(test.tx, generator.signer)
			require.ErrorContains(t, err, test.expectedError)
		})
	}
}

// testBundleGenerator allows to generate different types of bundle transactions
// for testing purposes.
// These include valid and invalid bundles, as well as non-bundle transactions.
type testBundleGenerator struct {
	keys   []*ecdsa.PrivateKey
	n      int
	signer types.Signer
}

// newTestBundleGenerator creates a new testBundleGenerator with n keys and a signer.
// the valid bundles generated by this generator will contain n transactions signed by the generated keys.
func newTestBundleGenerator(t testing.TB, n int) testBundleGenerator {
	t.Helper()
	keys := make([]*ecdsa.PrivateKey, n)
	for i := range keys {
		key, err := crypto.GenerateKey()
		require.NoError(t, err)
		keys[i] = key
	}

	return testBundleGenerator{
		keys:   keys,
		n:      n,
		signer: types.LatestSignerForChainID(testChainID),
	}
}

func (gen testBundleGenerator) makeEmptyBundleTx() *types.Transaction {
	bundle := TransactionBundle{
		Version: BundleV1,
		Bundle:  types.Transactions{},
		Flags:   0,
	}

	bytes := Encode(bundle)
	return types.NewTx(&types.LegacyTx{
		To:   &BundleAddress,
		Data: bytes,
	})
}

func (gen testBundleGenerator) makeValidBundleTx(t testing.TB) *types.Transaction {
	t.Helper()
	receiver := common.Address{0x42}

	//  Generate n metaTransactions from n different senders
	metaTransactions := make([]types.AccessListTx, gen.n)
	txHash := make([]common.Hash, gen.n)
	sender := make([]common.Address, gen.n)
	for i := range gen.n {
		tx := types.AccessListTx{
			Nonce: uint64(1),
			To:    &receiver,
			Value: big.NewInt(1234),
		}

		txHash[i] = gen.signer.Hash(types.NewTx(&tx))
		metaTransactions[i] = tx
		sender[i] = crypto.PubkeyToAddress(gen.keys[i].PublicKey)
	}

	// prepare execution  plan
	plan := ExecutionPlan{
		Steps: make([]ExecutionStep, gen.n),
		Flags: 0,
	}
	for i := range gen.n {
		plan.Steps[i] = ExecutionStep{
			From: sender[i],
			Hash: txHash[i],
		}
	}

	// amend transactions with the execution plan hash
	// and sign them
	planHash := plan.Hash()
	signedTransactions := make(types.Transactions, gen.n)
	for i := range gen.n {
		tx := metaTransactions[i]
		tx.AccessList = append(tx.AccessList, types.AccessTuple{
			Address: BundleOnly,
			StorageKeys: []common.Hash{
				planHash,
			},
		})

		signedTx, err := types.SignTx(types.NewTx(&tx), gen.signer, gen.keys[i])
		require.NoError(t, err)
		signedTransactions[i] = signedTx
	}

	// prepare the bundle
	bundle := TransactionBundle{
		Version: BundleV1,
		Bundle:  signedTransactions,
		Flags:   0,
	}

	return types.NewTx(&types.LegacyTx{
		To:   &BundleAddress,
		Data: Encode(bundle),
	})
}

func (gen testBundleGenerator) makeUnsoundBundleTx(t testing.TB) *types.Transaction {
	t.Helper()
	receiver := common.Address{0x42}

	// Generate n metaTransactions from n different senders
	// execution plan hash is not correct, therefore the bundle is unsound
	ExecutionPlanHash := common.Hash{0x99}
	signedTransactions := make(types.Transactions, gen.n)
	for i := range gen.n {
		tx := types.AccessListTx{
			Nonce: uint64(1),
			To:    &receiver,
			Value: big.NewInt(1234),
			AccessList: []types.AccessTuple{
				{
					Address: BundleOnly,
					StorageKeys: []common.Hash{
						ExecutionPlanHash,
					},
				},
			},
		}

		signedTx, err := types.SignTx(types.NewTx(&tx), gen.signer, gen.keys[i])
		require.NoError(t, err)
		signedTransactions[i] = signedTx
	}

	// prepare the bundle
	bundle := TransactionBundle{
		Version: BundleV1,
		Bundle:  signedTransactions,
		Flags:   0,
	}

	return types.NewTx(&types.LegacyTx{
		To:   &BundleAddress,
		Data: Encode(bundle),
	})

}

func (gen testBundleGenerator) makeBundleTxWithWronglySignedTx(t testing.TB) *types.Transaction {
	t.Helper()
	receiver := common.Address{0x42}

	ExecutionPlanHash := common.Hash{0x99}
	tx := types.AccessListTx{
		Nonce: uint64(1),
		To:    &receiver,
		Value: big.NewInt(1234),
		AccessList: []types.AccessTuple{
			{
				Address: BundleOnly,
				StorageKeys: []common.Hash{
					ExecutionPlanHash,
				},
			},
		},
	}

	// Transaction is not really signed, therefore the sender cannot be derived
	unsignedTransaction := types.NewTx(&tx)

	// prepare the bundle
	bundle := TransactionBundle{
		Version: BundleV1,
		Bundle:  []*types.Transaction{unsignedTransaction},
		Flags:   0,
	}

	return types.NewTx(&types.LegacyTx{
		To:   &BundleAddress,
		Data: Encode(bundle),
	})
}

func (gen testBundleGenerator) makeWrongVersionBundleTx() *types.Transaction {
	bundle := TransactionBundle{
		Version: 99, // unsupported version
		Bundle:  types.Transactions{},
		Flags:   0,
	}

	bytes := Encode(bundle)
	return types.NewTx(&types.LegacyTx{
		To:   &BundleAddress,
		Data: bytes,
	})
}

func (gen testBundleGenerator) makeNonBundleTx() *types.Transaction {
	someAddress := common.Address{0x42}
	return types.NewTx(&types.LegacyTx{
		To:   &someAddress,
		Data: []byte("this is not a bundle"),
	})
}
