// Copyright 2026 Sonic Operations Ltd
// This file is part of the Sonic Client
//
// Sonic is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Sonic is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with Sonic. If not, see <http://www.gnu.org/licenses/>.

package bundle

import (
	"crypto/ecdsa"
	"math/big"
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/stretchr/testify/require"
)

var testChainID = big.NewInt(1)

func TestValidate_IdentifiesBundles(t *testing.T) {

	generator := newTestBundleGenerator(t, 2)

	tests := map[string]struct {
		tx           *types.Transaction
		expectBundle bool
	}{
		"not a bundle": {tx: generator.makeNonBundleTx(), expectBundle: false},
		"empty bundle": {tx: generator.makeEmptyBundleTx(), expectBundle: true},
		"valid bundle": {tx: generator.makeValidBundleTx(), expectBundle: true},
	}

	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			bundle, plan, err := ValidateTransactionBundle(test.tx)
			require.NoError(t, err)
			if test.expectBundle {
				require.NotNil(t, bundle, "expected a bundle transaction")
				require.NotNil(t, plan, "expected an execution plan")
			} else {
				require.Nil(t, bundle, "expected no bundle transaction")
				require.Nil(t, plan, "expected no execution plan")
			}
		})
	}
}

func TestValidate_ReturnsErrorsOnValidationFailure(t *testing.T) {

	generator := newTestBundleGenerator(t, 2)

	tests := map[string]struct {
		tx            *types.Transaction
		expectedError string
	}{
		"unsound bundle": {
			tx:            generator.makeUnsoundBundleTx(t),
			expectedError: "does not belong to the execution plan",
		},
		"wrongly signed bundle": {
			tx:            generator.makeBundleTxWithWronglySignedTx(t),
			expectedError: "failed to derive sender",
		},
		"bundle without enough gas for intrinsic cost": {
			tx:            generator.makeBundleTxWithoutEnoughIntrinsicGas(),
			expectedError: "gas should be more",
		},
		"bundle without enough gas for all transactions": {
			tx:            generator.makeBundleTxWithoutEnoughGasForAllTransactions(),
			expectedError: "bundle gas limit",
		},
	}

	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			_, _, err := ValidateTransactionBundle(test.tx)
			require.ErrorContains(t, err, test.expectedError)
		})
	}
}

func TestValidate_AcceptsValidBlockRanges(t *testing.T) {

	tests := map[string]struct {
		From uint64
		To   uint64
		Gas  uint64
	}{
		"single-block range": {
			From: 10, To: 10, Gas: 21240,
		},
		"multi-block range": {
			From: 7, To: 42, Gas: 21240,
		},
		"max-size block range": {
			From: 100, To: 100 + MaxBlockRange - 1, Gas: 21320,
		},
	}

	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			data := Encode(TransactionBundle{
				Earliest: test.From,
				Latest:   test.To,
			})
			tx := types.NewTx(&types.LegacyTx{
				To:   &BundleProcessor,
				Data: data,
				Gas:  test.Gas,
			})
			require.True(t, IsEnvelope(tx))

			_, _, err := ValidateTransactionBundle(tx)
			require.NoError(t, err)
		})
	}
}

func TestValidate_IdentifiesInvalidBlockRanges(t *testing.T) {

	tests := map[string]struct {
		From  uint64
		To    uint64
		Issue string
	}{
		"empty block range": {
			From: 10, To: 5,
			Issue: "invalid empty block range [10,5] in execution plan",
		},
		"too large block range": {
			From: 7, To: 7 + MaxBlockRange,
			Issue: "invalid block range in execution plan, duration 1025, limit 1024",
		},
	}

	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			data := Encode(TransactionBundle{
				Earliest: test.From,
				Latest:   test.To,
			})
			tx := types.NewTx(&types.LegacyTx{
				To:   &BundleProcessor,
				Data: data,
			})
			require.True(t, IsEnvelope(tx))

			_, _, err := ValidateTransactionBundle(tx)
			require.ErrorContains(t, err, test.Issue)
		})
	}
}

// testBundleGenerator allows to generate different types of bundle transactions
// for testing purposes.
// These include valid and invalid bundles, as well as non-bundle transactions.
type testBundleGenerator struct {
	keys []*ecdsa.PrivateKey
	n    int
}

// newTestBundleGenerator creates a new testBundleGenerator with n keys and a signer.
// the valid bundles generated by this generator will contain n transactions signed by the generated keys.
func newTestBundleGenerator(t testing.TB, n int) testBundleGenerator {
	t.Helper()
	keys := make([]*ecdsa.PrivateKey, n)
	for i := range keys {
		key, err := crypto.GenerateKey()
		require.NoError(t, err)
		keys[i] = key
	}

	return testBundleGenerator{
		keys: keys,
		n:    n,
	}
}

func (gen testBundleGenerator) makeEmptyBundleTx() *types.Transaction {
	return AllOf()
}

func (gen testBundleGenerator) makeValidBundleTx() *types.Transaction {
	receiver := common.Address{0x42}
	gasPerTx := uint64(20_000)

	steps := make([]BundleStep, 0, gen.n)
	for i := range gen.n {
		steps = append(steps, Step(gen.keys[i], &types.AccessListTx{
			Nonce: uint64(1),
			To:    &receiver,
			Value: big.NewInt(1234),
			Gas:   gasPerTx,
		}))
	}

	return AllOf(steps...)
}

func (gen testBundleGenerator) makeUnsoundBundleTx(t testing.TB) *types.Transaction {
	t.Helper()
	receiver := common.Address{0x42}

	signer := types.LatestSignerForChainID(testChainID)

	// Generate n metaTransactions from n different senders
	// execution plan hash is not correct, therefore the bundle is unsound
	executionPlanHash := common.Hash{0x99}
	signedTransactions := make(types.Transactions, gen.n)
	for i := range gen.n {
		tx := types.AccessListTx{
			Nonce: uint64(1),
			To:    &receiver,
			Value: big.NewInt(1234),
			AccessList: []types.AccessTuple{
				{
					Address: BundleOnly,
					StorageKeys: []common.Hash{
						executionPlanHash,
					},
				},
			},
		}

		signedTx, err := types.SignTx(types.NewTx(&tx), signer, gen.keys[i])
		require.NoError(t, err)
		signedTransactions[i] = signedTx
	}

	// prepare the bundle
	bundle := TransactionBundle{
		Bundle: signedTransactions,
		Flags:  0,
	}

	return types.NewTx(&types.LegacyTx{
		To:   &BundleProcessor,
		Data: Encode(bundle),
		Gas:  21096,
	})

}

func (gen testBundleGenerator) makeBundleTxWithWronglySignedTx(t testing.TB) *types.Transaction {
	t.Helper()
	receiver := common.Address{0x42}

	ExecutionPlanHash := common.Hash{0x99}
	tx := types.AccessListTx{
		Nonce: uint64(1),
		To:    &receiver,
		Value: big.NewInt(1234),
		AccessList: []types.AccessTuple{
			{
				Address: BundleOnly,
				StorageKeys: []common.Hash{
					ExecutionPlanHash,
				},
			},
		},
	}

	// Transaction is not really signed, therefore the sender cannot be derived
	unsignedTransaction := types.NewTx(&tx)

	// prepare the bundle
	bundle := TransactionBundle{
		Bundle: []*types.Transaction{unsignedTransaction},
		Flags:  0,
	}

	return types.NewTx(&types.LegacyTx{
		To:   &BundleProcessor,
		Data: Encode(bundle),
		Gas:  21096,
	})
}

func (gen testBundleGenerator) makeNonBundleTx() *types.Transaction {
	someAddress := common.Address{0x42}
	return types.NewTx(&types.LegacyTx{
		To:   &someAddress,
		Data: []byte("this is not a bundle"),
		Gas:  21096,
	})
}

func (gen testBundleGenerator) makeBundleTxWithoutEnoughIntrinsicGas() *types.Transaction {
	tx := gen.makeValidBundleTx()
	// reduce the gas in tx
	tx = types.NewTx(&types.LegacyTx{
		To:   &BundleProcessor,
		Data: tx.Data(),
		Gas:  10_000, // not enough gas for the bundle
	})
	return tx
}

func (gen testBundleGenerator) makeBundleTxWithoutEnoughGasForAllTransactions() *types.Transaction {
	tx := gen.makeValidBundleTx()
	// reduce the gas in tx
	tx = types.NewTx(&types.LegacyTx{
		To:   &BundleProcessor,
		Data: tx.Data(),
		Gas:  35_000, // not enough gas for all transactions in the bundle
	})
	return tx
}
