// Copyright 2026 Sonic Operations Ltd
// This file is part of the Sonic Client
//
// Sonic is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Sonic is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with Sonic. If not, see <http://www.gnu.org/licenses/>.

package bundle

import (
	"crypto/ecdsa"
	"errors"
	"fmt"
	"math/big"
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/stretchr/testify/require"
	gomock "go.uber.org/mock/gomock"
)

var testChainID = big.NewInt(1)

func TestValidate_IdentifiesBundles(t *testing.T) {

	generator := newTestBundleGenerator(t, 2)

	tests := map[string]struct {
		tx           *types.Transaction
		expectBundle bool
	}{
		"not a bundle": {tx: generator.makeNonBundleTx(), expectBundle: false},
		"empty bundle": {tx: generator.makeEmptyBundleTx(), expectBundle: true},
		"valid bundle": {tx: generator.makeValidBundleTx(), expectBundle: true},
	}

	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			bundle, plan, err := ValidateTransactionBundle(test.tx)
			require.NoError(t, err)
			if test.expectBundle {
				require.NotNil(t, bundle, "expected a bundle transaction")
				require.NotNil(t, plan, "expected an execution plan")
			} else {
				require.Nil(t, bundle, "expected no bundle transaction")
				require.Nil(t, plan, "expected no execution plan")
			}
		})
	}
}

func TestValidate_ReturnsErrorsOnValidationFailure(t *testing.T) {

	generator := newTestBundleGenerator(t, 2)

	tests := map[string]struct {
		tx            *types.Transaction
		expectedError string
	}{
		"unsound bundle": {
			tx:            generator.makeUnsoundBundleTx(t),
			expectedError: "does not belong to the execution plan",
		},
		"wrongly signed bundle": {
			tx:            generator.makeBundleTxWithWronglySignedTx(t),
			expectedError: "failed to derive sender",
		},
		"bundle without enough gas for intrinsic cost": {
			tx:            generator.makeBundleTxWithoutEnoughIntrinsicGas(),
			expectedError: "gas should be more",
		},
		"bundle without enough gas for all transactions": {
			tx:            generator.makeBundleTxWithoutEnoughGasForAllTransactions(),
			expectedError: "bundle gas limit",
		},
	}

	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			_, _, err := ValidateTransactionBundle(test.tx)
			require.ErrorContains(t, err, test.expectedError)
		})
	}
}

func TestValidate_AcceptsValidBlockRanges(t *testing.T) {

	tests := map[string]struct {
		From uint64
		To   uint64
		Gas  uint64
	}{
		"single-block range": {
			From: 10, To: 10, Gas: 21240,
		},
		"multi-block range": {
			From: 7, To: 42, Gas: 21240,
		},
		"max-size block range": {
			From: 100, To: 100 + MaxBlockRange - 1, Gas: 21320,
		},
	}

	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			data := TransactionBundle{
				Earliest: test.From,
				Latest:   test.To,
			}.Encode()
			tx := types.NewTx(&types.LegacyTx{
				To:   &BundleProcessor,
				Data: data,
				Gas:  test.Gas,
			})
			require.True(t, IsEnvelope(tx))

			_, _, err := ValidateTransactionBundle(tx)
			require.NoError(t, err)
		})
	}
}

func TestValidate_IdentifiesInvalidBlockRanges(t *testing.T) {

	tests := map[string]struct {
		From  uint64
		To    uint64
		Issue string
	}{
		"empty block range": {
			From: 10, To: 5,
			Issue: "invalid empty block range [10,5] in execution plan",
		},
		"too large block range": {
			From: 7, To: 7 + MaxBlockRange,
			Issue: "invalid block range in execution plan, duration 1025, limit 1024",
		},
	}

	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			data := TransactionBundle{
				Earliest: test.From,
				Latest:   test.To,
			}.Encode()
			tx := types.NewTx(&types.LegacyTx{
				To:   &BundleProcessor,
				Data: data,
			})
			require.True(t, IsEnvelope(tx))

			_, _, err := ValidateTransactionBundle(tx)
			require.ErrorContains(t, err, test.Issue)
		})
	}
}

// testBundleGenerator allows to generate different types of bundle transactions
// for testing purposes.
// These include valid and invalid bundles, as well as non-bundle transactions.
type testBundleGenerator struct {
	keys []*ecdsa.PrivateKey
	n    int
}

// newTestBundleGenerator creates a new testBundleGenerator with n keys and a signer.
// the valid bundles generated by this generator will contain n transactions signed by the generated keys.
func newTestBundleGenerator(t testing.TB, n int) testBundleGenerator {
	t.Helper()
	keys := make([]*ecdsa.PrivateKey, n)
	for i := range keys {
		key, err := crypto.GenerateKey()
		require.NoError(t, err)
		keys[i] = key
	}

	return testBundleGenerator{
		keys: keys,
		n:    n,
	}
}

func (gen testBundleGenerator) makeEmptyBundleTx() *types.Transaction {
	return AllOf()
}

func (gen testBundleGenerator) makeValidBundleTx() *types.Transaction {
	receiver := common.Address{0x42}
	gasPerTx := uint64(20_000)

	steps := make([]BundleStep, 0, gen.n)
	for i := range gen.n {
		steps = append(steps, Step(gen.keys[i], &types.AccessListTx{
			Nonce: uint64(1),
			To:    &receiver,
			Value: big.NewInt(1234),
			Gas:   gasPerTx,
		}))
	}

	return AllOf(steps...)
}

func (gen testBundleGenerator) makeUnsoundBundleTx(t testing.TB) *types.Transaction {
	t.Helper()
	receiver := common.Address{0x42}

	signer := types.LatestSignerForChainID(testChainID)

	// Generate n metaTransactions from n different senders
	// execution plan hash is not correct, therefore the bundle is unsound
	invalidExecutionPlanHash := common.Hash{0x99}
	signedTransactions := make(types.Transactions, gen.n)
	for i := range gen.n {
		tx := types.AccessListTx{
			Nonce: uint64(1),
			To:    &receiver,
			Value: big.NewInt(1234),
			AccessList: []types.AccessTuple{
				{
					Address: BundleOnly,
					StorageKeys: []common.Hash{
						invalidExecutionPlanHash,
					},
				},
			},
		}

		signedTx, err := types.SignTx(types.NewTx(&tx), signer, gen.keys[i])
		require.NoError(t, err)
		signedTransactions[i] = signedTx
	}

	// prepare the bundle
	bundle := TransactionBundle{
		Transactions: signedTransactions,
		Flags:        0,
	}

	return types.NewTx(&types.LegacyTx{
		To:   &BundleProcessor,
		Data: bundle.Encode(),
		Gas:  21096,
	})

}

func (gen testBundleGenerator) makeBundleTxWithWronglySignedTx(t testing.TB) *types.Transaction {
	t.Helper()
	receiver := common.Address{0x42}

	ExecutionPlanHash := common.Hash{0x99}
	tx := types.AccessListTx{
		Nonce: uint64(1),
		To:    &receiver,
		Value: big.NewInt(1234),
		AccessList: []types.AccessTuple{
			{
				Address: BundleOnly,
				StorageKeys: []common.Hash{
					ExecutionPlanHash,
				},
			},
		},
	}

	// Transaction is not really signed, therefore the sender cannot be derived
	unsignedTransaction := types.NewTx(&tx)

	// prepare the bundle
	bundle := TransactionBundle{
		Transactions: []*types.Transaction{unsignedTransaction},
		Flags:        0,
	}

	return types.NewTx(&types.LegacyTx{
		To:   &BundleProcessor,
		Data: bundle.Encode(),
		Gas:  21096,
	})
}

func (gen testBundleGenerator) makeNonBundleTx() *types.Transaction {
	someAddress := common.Address{0x42}
	return types.NewTx(&types.LegacyTx{
		To:   &someAddress,
		Data: []byte("this is not a bundle"),
		Gas:  21096,
	})
}

func (gen testBundleGenerator) makeBundleTxWithoutEnoughIntrinsicGas() *types.Transaction {
	tx := gen.makeValidBundleTx()
	// reduce the gas in tx
	tx = types.NewTx(&types.LegacyTx{
		To:   &BundleProcessor,
		Data: tx.Data(),
		Gas:  10_000, // not enough gas for the bundle
	})
	return tx
}

func (gen testBundleGenerator) makeBundleTxWithoutEnoughGasForAllTransactions() *types.Transaction {
	tx := gen.makeValidBundleTx()
	// reduce the gas in tx
	tx = types.NewTx(&types.LegacyTx{
		To:   &BundleProcessor,
		Data: tx.Data(),
		Gas:  35_000, // not enough gas for all transactions in the bundle
	})
	return tx
}

func TestBelongsToExecutionPlan_IdentifiesTransactionsWhichSignTheExecutionPlan(t *testing.T) {

	executionPlanHash := common.Hash{0x01, 0x02, 0x03}

	tests := map[string]struct {
		tx                types.TxData
		executionPlanHash common.Hash
		expected          bool
	}{
		"transaction without access list": {
			tx:       &types.LegacyTx{},
			expected: false,
		},
		"transaction with bundle-only but no plan hash": {
			tx: &types.AccessListTx{
				AccessList: types.AccessList{
					{
						Address: BundleOnly,
					},
				},
			},
			executionPlanHash: executionPlanHash,
			expected:          false,
		},
		"fragmented access list": {
			tx: &types.AccessListTx{
				AccessList: types.AccessList{
					{
						Address: BundleOnly,
					},
					{
						Address:     common.HexToAddress("0x0000000000000000000000000000000000000001"),
						StorageKeys: []common.Hash{executionPlanHash},
					},
				},
			},
			executionPlanHash: executionPlanHash,
			expected:          false,
		},
		"transaction with bundle-only and matching plan hash": {
			tx: &types.AccessListTx{
				AccessList: types.AccessList{
					{
						Address:     BundleOnly,
						StorageKeys: []common.Hash{executionPlanHash},
					},
				},
			},
			executionPlanHash: executionPlanHash,
			expected:          true,
		},
		"transaction with multiple accepted plans": {
			tx: &types.AccessListTx{
				AccessList: types.AccessList{
					{
						Address:     BundleOnly,
						StorageKeys: []common.Hash{{0x0A}},
					},
					{
						Address:     BundleOnly,
						StorageKeys: []common.Hash{executionPlanHash},
					},
					{
						Address:     BundleOnly,
						StorageKeys: []common.Hash{{0x0B}},
					},
				},
			},
			executionPlanHash: executionPlanHash,
			expected:          true,
		},
		"transaction with multiple accepted plans compact": {
			tx: &types.AccessListTx{
				AccessList: types.AccessList{
					{
						Address:     BundleOnly,
						StorageKeys: []common.Hash{{0x0A}, executionPlanHash, {0x0B}},
					},
				},
			},
			executionPlanHash: executionPlanHash,
			expected:          true,
		},
	}

	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			tx := types.NewTx(test.tx)
			require.Equal(t, test.expected,
				belongsToExecutionPlan(tx, test.executionPlanHash))
		})
	}

}

func TestExtractExecutionPlan_ExtractsStepsAndFlags(t *testing.T) {
	key, err := crypto.GenerateKey()
	require.NoError(t, err)

	for _, flags := range []ExecutionFlag{0, 1, 2, 3} {
		for _, earliest := range []uint64{1, 5, 20} {
			for _, latest := range []uint64{50, 100, 200} {
				bundle := NewBuilder().
					WithFlags(flags).
					Earliest(earliest).
					Latest(latest).
					With(
						Step(key, &types.AccessListTx{}),
						Step(key, &types.AccessListTx{}),
					).BuildBundle()

				ctrl := gomock.NewController(t)
				mockSigner := NewMockSigner(ctrl)
				mockSigner.EXPECT().Sender(gomock.Any()).Return(common.Address{0x42}, nil)
				mockSigner.EXPECT().Sender(gomock.Any()).Return(common.Address{0x43}, nil)
				mockSigner.EXPECT().Hash(gomock.Any()).Return(common.Hash{0x01})
				mockSigner.EXPECT().Hash(gomock.Any()).Return(common.Hash{0x02})

				executionPlan, err := bundle.extractExecutionPlan(mockSigner)
				require.NoError(t, err)

				require.Equal(t, 2, len(executionPlan.Steps))
				require.Equal(t, common.Address{0x42}, executionPlan.Steps[0].From)
				require.Equal(t, common.Hash{0x01}, executionPlan.Steps[0].Hash)
				require.Equal(t, common.Address{0x43}, executionPlan.Steps[1].From)
				require.Equal(t, common.Hash{0x02}, executionPlan.Steps[1].Hash)
				require.Equal(t, bundle.Flags, executionPlan.Flags)
				require.Equal(t, bundle.Earliest, executionPlan.Earliest)
				require.Equal(t, bundle.Latest, executionPlan.Latest)
			}
		}
	}
}

func TestExtractExecutionPlan_ComputesHashOfUnmarkedBundledTransactions(t *testing.T) {
	// This test verifies that the hash of transactions included in the execution plan
	// correspond to the hash of the transaction without the bundle-only marker in the access list.

	txs := []types.TxData{

		&types.AccessListTx{
			Nonce:    1,
			GasPrice: big.NewInt(100),
			Gas:      21000,
			To:       &common.Address{0x01},
			Value:    big.NewInt(100),
			Data:     []byte{0x01, 0x02},
			AccessList: types.AccessList{
				{
					Address:     BundleOnly,
					StorageKeys: []common.Hash{{0x01}},
				},
				{
					Address: common.HexToAddress("0x0000000000000000000000000000000000000001"),
				},
			},
		},

		&types.DynamicFeeTx{
			Nonce:     2,
			GasTipCap: big.NewInt(100),
			GasFeeCap: big.NewInt(200),
			Gas:       21000,
			To:        &common.Address{0x02},
			Value:     big.NewInt(100),
			Data:      []byte{0x03, 0x04},
			AccessList: types.AccessList{
				{
					Address:     BundleOnly,
					StorageKeys: []common.Hash{{0x01}},
				},
				{
					Address: common.HexToAddress("0x0000000000000000000000000000000000000002"),
				},
			},
		},
	}

	key, err := crypto.GenerateKey()
	require.NoError(t, err)
	signer := types.LatestSignerForChainID(big.NewInt(1))

	for _, txData := range txs {

		tx, err := types.SignNewTx(key, signer, txData)
		require.NoError(t, err)

		bundle := TransactionBundle{
			Transactions: types.Transactions{tx},
		}
		executionPlan, err := bundle.extractExecutionPlan(signer)
		require.NoError(t, err)

		require.Equal(t, 1, len(executionPlan.Steps))

		withoutBundleOnlyMark, err := removeBundleOnlyMark(types.NewTx(txData))
		require.NoError(t, err)

		hash := signer.Hash(withoutBundleOnlyMark)
		require.Equal(t, hash, executionPlan.Steps[0].Hash)
	}
}

func TestExtractExecutionPlan_ReturnsErrorWithUnsupportedTransactionType(t *testing.T) {

	tests := []types.TxData{
		&types.LegacyTx{},
		&types.BlobTx{},
		&types.SetCodeTx{},
	}

	for _, txData := range tests {

		tx := types.NewTx(txData)
		bundle := TransactionBundle{
			Transactions: types.Transactions{tx},
		}

		ctrl := gomock.NewController(t)
		mockSigner := NewMockSigner(ctrl)
		mockSigner.EXPECT().Sender(gomock.Any()).Return(common.Address{}, nil)

		_, err := bundle.extractExecutionPlan(mockSigner)
		require.ErrorContains(t, err,
			fmt.Sprintf("invalid bundle: unsupported transaction type %d", tx.Type()))
	}
}

func TestExtractExecutionPlan_ReturnsErrorWithMalformedSignature(t *testing.T) {

	bundle := TransactionBundle{
		Transactions: types.Transactions{
			types.NewTx(&types.AccessListTx{
				AccessList: types.AccessList{
					{
						Address:     BundleOnly,
						StorageKeys: []common.Hash{{0x01}},
					},
				},
			}),
		},
	}

	ctrl := gomock.NewController(t)
	mockSigner := NewMockSigner(ctrl)
	mockSigner.EXPECT().Sender(gomock.Any()).Return(common.Address{}, errors.New("invalid signature"))

	_, err := bundle.extractExecutionPlan(mockSigner)
	require.ErrorContains(t, err, "failed to derive sender: invalid signature")
}

func TestRemoveBundleOnlyMark_ReturnsErrorWithUnsupportedTransactionType(t *testing.T) {
	tests := []types.TxData{
		&types.LegacyTx{},
		&types.BlobTx{},
		&types.SetCodeTx{},
	}

	for _, txData := range tests {
		tx := types.NewTx(txData)
		_, err := removeBundleOnlyMark(tx)
		require.ErrorContains(t, err,
			fmt.Sprintf("invalid bundle: unsupported transaction type %d", tx.Type()))
	}
}

func TestRemoveBundleOnlyMark_PreservesOriginalData(t *testing.T) {

	type msg struct {
		Nonce      uint64
		GasPrice   *big.Int
		Gas        uint64
		To         *common.Address
		Value      *big.Int
		Data       []byte
		AccessList types.AccessList
	}

	normalAccessListEntry := types.AccessList{
		{
			Address:     common.HexToAddress("0x0000000000000000000000000000000000000001"),
			StorageKeys: []common.Hash{{0x01}, {0x02}},
		},
	}
	bundleOnlyMark := types.AccessList{
		{
			Address:     BundleOnly,
			StorageKeys: []common.Hash{{0x01}},
		},
	}

	tests := make([]msg, 0)
	for _, gasPrice := range []*big.Int{nil, big.NewInt(0), big.NewInt(200)} {
		for _, gas := range []uint64{0, 21000} {
			for _, to := range []*common.Address{nil, {0x01}} {
				for _, value := range []*big.Int{nil, big.NewInt(0), big.NewInt(100)} {
					for _, accessList := range []types.AccessList{
						nil,
						normalAccessListEntry,
					} {

						tests = append(tests, msg{
							Nonce:      1,
							GasPrice:   gasPrice,
							Gas:        gas,
							To:         to,
							Value:      value,
							Data:       []byte{0x01, 0x02},
							AccessList: accessList,
						})
					}
				}
			}
		}
	}

	for _, test := range tests {

		t.Run("preserves original members of the access list transaction", func(t *testing.T) {

			txData := &types.AccessListTx{
				Nonce:      test.Nonce,
				GasPrice:   test.GasPrice,
				Gas:        test.Gas,
				To:         test.To,
				Value:      test.Value,
				Data:       test.Data,
				AccessList: test.AccessList,
			}

			tx := types.NewTx(txData)
			modified, err := removeBundleOnlyMark(tx)
			require.NoError(t, err)

			if test.GasPrice == nil {
				test.GasPrice = big.NewInt(0)
			}
			if test.Value == nil {
				test.Value = big.NewInt(0)
			}
			if test.AccessList == nil {
				test.AccessList = types.AccessList{}
			}

			require.Equal(t, test.Nonce, modified.Nonce())
			require.Equal(t, test.GasPrice, modified.GasPrice())
			require.Equal(t, test.Gas, modified.Gas())
			require.Equal(t, test.To, modified.To())
			require.Equal(t, test.Value, modified.Value())
			require.Equal(t, test.Data, modified.Data())
			require.Equal(t, test.AccessList, modified.AccessList())
		})

		t.Run("removes bundle marker from the access list transaction", func(t *testing.T) {

			txData := &types.AccessListTx{
				Nonce:      test.Nonce,
				GasPrice:   test.GasPrice,
				Gas:        test.Gas,
				To:         test.To,
				Value:      test.Value,
				Data:       test.Data,
				AccessList: append(test.AccessList, bundleOnlyMark...),
			}

			tx := types.NewTx(txData)
			modified, err := removeBundleOnlyMark(tx)
			require.NoError(t, err)

			if test.AccessList == nil {
				test.AccessList = types.AccessList{}
			}

			require.Equal(t, test.AccessList, modified.AccessList())
		})

		t.Run("preserves original members of the dynamic fees transaction", func(t *testing.T) {

			txData := &types.DynamicFeeTx{
				Nonce:      test.Nonce,
				GasFeeCap:  test.GasPrice,
				GasTipCap:  test.GasPrice,
				Gas:        test.Gas,
				To:         test.To,
				Value:      test.Value,
				Data:       test.Data,
				AccessList: test.AccessList,
			}

			tx := types.NewTx(txData)
			modified, err := removeBundleOnlyMark(tx)
			require.NoError(t, err)

			if test.GasPrice == nil {
				test.GasPrice = big.NewInt(0)
			}
			if test.Value == nil {
				test.Value = big.NewInt(0)
			}
			if test.AccessList == nil {
				test.AccessList = types.AccessList{}
			}

			require.Equal(t, test.Nonce, modified.Nonce())
			require.Equal(t, test.GasPrice, modified.GasFeeCap())
			require.Equal(t, test.GasPrice, modified.GasTipCap())
			require.Equal(t, test.Gas, modified.Gas())
			require.Equal(t, test.To, modified.To())
			require.Equal(t, test.Value, modified.Value())
			require.Equal(t, test.Data, modified.Data())
			require.Equal(t, test.AccessList, modified.AccessList())
		})

		t.Run("removes bundle marker from the dynamic fee transaction", func(t *testing.T) {

			txData := &types.DynamicFeeTx{
				Nonce:      test.Nonce,
				GasFeeCap:  test.GasPrice,
				GasTipCap:  test.GasPrice,
				Gas:        test.Gas,
				To:         test.To,
				Value:      test.Value,
				Data:       test.Data,
				AccessList: append(test.AccessList, bundleOnlyMark...),
			}

			tx := types.NewTx(txData)
			modified, err := removeBundleOnlyMark(tx)
			require.NoError(t, err)

			if test.AccessList == nil {
				test.AccessList = types.AccessList{}
			}

			require.Equal(t, test.AccessList, modified.AccessList())
		})
	}
}

//go:generate mockgen -source=validate_test.go -destination=validate_test_mock.go -package=bundle

type Signer interface {
	types.Signer
}
