// Code generated by MockGen. DO NOT EDIT.
// Source: metrics.go
//
// Generated by this command:
//
//	mockgen -source=metrics.go -destination=metrics_mock.go -package=utils
//

// Package utils is a generated GoMock package.
package utils

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetricsHistogramWrapper is a mock of MetricsHistogramWrapper interface.
type MockMetricsHistogramWrapper struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsHistogramWrapperMockRecorder
	isgomock struct{}
}

// MockMetricsHistogramWrapperMockRecorder is the mock recorder for MockMetricsHistogramWrapper.
type MockMetricsHistogramWrapperMockRecorder struct {
	mock *MockMetricsHistogramWrapper
}

// NewMockMetricsHistogramWrapper creates a new mock instance.
func NewMockMetricsHistogramWrapper(ctrl *gomock.Controller) *MockMetricsHistogramWrapper {
	mock := &MockMetricsHistogramWrapper{ctrl: ctrl}
	mock.recorder = &MockMetricsHistogramWrapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsHistogramWrapper) EXPECT() *MockMetricsHistogramWrapperMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockMetricsHistogramWrapper) Update(arg0 float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", arg0)
}

// Update indicates an expected call of Update.
func (mr *MockMetricsHistogramWrapperMockRecorder) Update(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMetricsHistogramWrapper)(nil).Update), arg0)
}

// MockMetricsHistogramWrapper is a mock of MetricsHistogramWrapper interface.
type MockMetricsHistogramWrapper struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsHistogramWrapperMockRecorder
	isgomock struct{}
}

// MockMetricsHistogramWrapperMockRecorder is the mock recorder for MockMetricsHistogramWrapper.
type MockMetricsHistogramWrapperMockRecorder struct {
	mock *MockMetricsHistogramWrapper
}

// NewMockMetricsHistogramWrapper creates a new mock instance.
func NewMockMetricsHistogramWrapper(ctrl *gomock.Controller) *MockMetricsHistogramWrapper {
	mock := &MockMetricsHistogramWrapper{ctrl: ctrl}
	mock.recorder = &MockMetricsHistogramWrapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsHistogramWrapper) EXPECT() *MockMetricsHistogramWrapperMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockMetricsHistogramWrapper) Update(arg0 int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", arg0)
}

// Update indicates an expected call of Update.
func (mr *MockMetricsHistogramWrapperMockRecorder) Update(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMetricsHistogramWrapper)(nil).Update), arg0)
}
