// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.21.12
// source: validator_directory.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ValidatorAdvertisement is published by a validator on the validator-directory
// gossip topic, binding its consensus identity to its network location so other
// validators can discover where to dial it for the full mesh.
type ValidatorAdvertisement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The secp256k1 consensus public key of the advertising validator.
	ValidatorPublicKey []byte `protobuf:"bytes,1,opt,name=validator_public_key,json=validatorPublicKey,proto3" json:"validator_public_key,omitempty"`
	// The libp2p peer ID (raw bytes) of the advertising validator.
	PeerId []byte `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// The dialable multiaddrs of the validator (without the peer ID component).
	Addresses []string `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// A strictly-increasing freshness counter. It is seeded from the wall clock
	// at start so it remains monotonic across restarts; receivers accept an
	// advertisement only if its sequence exceeds the last one stored.
	Sequence uint64 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// The consensus-key signature over the domain-separated, length-prefixed
	// digest of the peer ID, addresses, and sequence.
	Signature []byte `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *ValidatorAdvertisement) Reset() {
	*x = ValidatorAdvertisement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_validator_directory_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidatorAdvertisement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorAdvertisement) ProtoMessage() {}

func (x *ValidatorAdvertisement) ProtoReflect() protoreflect.Message {
	mi := &file_validator_directory_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorAdvertisement.ProtoReflect.Descriptor instead.
func (*ValidatorAdvertisement) Descriptor() ([]byte, []int) {
	return file_validator_directory_proto_rawDescGZIP(), []int{0}
}

func (x *ValidatorAdvertisement) GetValidatorPublicKey() []byte {
	if x != nil {
		return x.ValidatorPublicKey
	}
	return nil
}

func (x *ValidatorAdvertisement) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *ValidatorAdvertisement) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *ValidatorAdvertisement) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ValidatorAdvertisement) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_validator_directory_proto protoreflect.FileDescriptor

var file_validator_directory_proto_rawDesc = []byte{
	0x0a, 0x19, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x73, 0x6f, 0x6e,
	0x69, 0x63, 0x2e, 0x70, 0x32, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbb, 0x01, 0x0a,
	0x16, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74,
	0x69, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x14, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x6f, 0x72, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x12, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_validator_directory_proto_rawDescOnce sync.Once
	file_validator_directory_proto_rawDescData = file_validator_directory_proto_rawDesc
)

func file_validator_directory_proto_rawDescGZIP() []byte {
	file_validator_directory_proto_rawDescOnce.Do(func() {
		file_validator_directory_proto_rawDescData = protoimpl.X.CompressGZIP(file_validator_directory_proto_rawDescData)
	})
	return file_validator_directory_proto_rawDescData
}

var file_validator_directory_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_validator_directory_proto_goTypes = []interface{}{
	(*ValidatorAdvertisement)(nil), // 0: sonic.p2p.proto.ValidatorAdvertisement
}
var file_validator_directory_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_validator_directory_proto_init() }
func file_validator_directory_proto_init() {
	if File_validator_directory_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_validator_directory_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidatorAdvertisement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_validator_directory_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_validator_directory_proto_goTypes,
		DependencyIndexes: file_validator_directory_proto_depIdxs,
		MessageInfos:      file_validator_directory_proto_msgTypes,
	}.Build()
	File_validator_directory_proto = out.File
	file_validator_directory_proto_rawDesc = nil
	file_validator_directory_proto_goTypes = nil
	file_validator_directory_proto_depIdxs = nil
}
