// Code generated by MockGen. DO NOT EDIT.
// Source: carmen.go
//
// Generated by this command:
//
//	mockgen -source=carmen.go -destination=carmen_mock.go -package=evmstore
//

// Package evmstore is a generated GoMock package.
package evmstore

import (
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockProcessedBundleStore is a mock of ProcessedBundleStore interface.
type MockProcessedBundleStore struct {
	ctrl     *gomock.Controller
	recorder *MockProcessedBundleStoreMockRecorder
	isgomock struct{}
}

// MockProcessedBundleStoreMockRecorder is the mock recorder for MockProcessedBundleStore.
type MockProcessedBundleStoreMockRecorder struct {
	mock *MockProcessedBundleStore
}

// NewMockProcessedBundleStore creates a new mock instance.
func NewMockProcessedBundleStore(ctrl *gomock.Controller) *MockProcessedBundleStore {
	mock := &MockProcessedBundleStore{ctrl: ctrl}
	mock.recorder = &MockProcessedBundleStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessedBundleStore) EXPECT() *MockProcessedBundleStoreMockRecorder {
	return m.recorder
}

// HasBeenProcessed mocks base method.
func (m *MockProcessedBundleStore) HasBeenProcessed(execPlanHash common.Hash) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasBeenProcessed", execPlanHash)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasBeenProcessed indicates an expected call of HasBeenProcessed.
func (mr *MockProcessedBundleStoreMockRecorder) HasBeenProcessed(execPlanHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasBeenProcessed", reflect.TypeOf((*MockProcessedBundleStore)(nil).HasBeenProcessed), execPlanHash)
}
