// Code generated by MockGen. DO NOT EDIT.
// Source: bundle_api.go
//
// Generated by this command:
//
//	mockgen -source=bundle_api.go -destination=bundle_api_mock.go -package=ethapi
//

// Package ethapi is a generated GoMock package.
package ethapi

import (
	reflect "reflect"

	hexutil "github.com/ethereum/go-ethereum/common/hexutil"
	gomock "go.uber.org/mock/gomock"
)

// MockGasEstimator is a mock of GasEstimator interface.
type MockGasEstimator struct {
	ctrl     *gomock.Controller
	recorder *MockGasEstimatorMockRecorder
	isgomock struct{}
}

// MockGasEstimatorMockRecorder is the mock recorder for MockGasEstimator.
type MockGasEstimatorMockRecorder struct {
	mock *MockGasEstimator
}

// NewMockGasEstimator creates a new mock instance.
func NewMockGasEstimator(ctrl *gomock.Controller) *MockGasEstimator {
	mock := &MockGasEstimator{ctrl: ctrl}
	mock.recorder = &MockGasEstimatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGasEstimator) EXPECT() *MockGasEstimatorMockRecorder {
	return m.recorder
}

// EstimateGas mocks base method.
func (m *MockGasEstimator) EstimateGas(args TransactionArgs, preArgs []TransactionArgs) (hexutil.Uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateGas", args, preArgs)
	ret0, _ := ret[0].(hexutil.Uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateGas indicates an expected call of EstimateGas.
func (mr *MockGasEstimatorMockRecorder) EstimateGas(args, preArgs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateGas", reflect.TypeOf((*MockGasEstimator)(nil).EstimateGas), args, preArgs)
}
