// Copyright 2026 Sonic Operations Ltd
// This file is part of the Sonic Client
//
// Sonic is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Sonic is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with Sonic. If not, see <http://www.gnu.org/licenses/>.

package ethapi

import (
	"context"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"hash/crc32"
	"maps"
	"math"
	"math/big"
	"testing"

	"github.com/0xsoniclabs/sonic/evmcore"
	priorityRegistry "github.com/0xsoniclabs/sonic/gossip/blockproc/priorities/registry"
	subsidiesRegistry "github.com/0xsoniclabs/sonic/gossip/blockproc/subsidies/registry"
	"github.com/0xsoniclabs/sonic/inter"
	"github.com/0xsoniclabs/sonic/opera"
	"github.com/Fantom-foundation/lachesis-base/inter/idx"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
	"github.com/ethereum/go-ethereum/params"
	"github.com/ethereum/go-ethereum/rlp"
	"github.com/ethereum/go-ethereum/rpc"
	"github.com/stretchr/testify/require"
	"go.uber.org/mock/gomock"
)

func TestForkId_FollowsFormula(t *testing.T) {
	// this test verifies that the ForkId generated by MakeForkId follows the formula:
	// CRC32(genesisId || bigEndian(upgrade.Height) || Rlp(upgrade))

	blockHeights := []idx.Block{1, 5, 10}
	genesisHashes := []common.Hash{{0x42}, {0x43}, {0x44}}
	for name, upgrades := range opera.GetAllHardForksInOrder() {
		for _, blockHeight := range blockHeights {
			for _, genesisHash := range genesisHashes {
				t.Run(fmt.Sprintf("%s-%v-%s", name, blockHeight, genesisHash.String()),
					func(t *testing.T) {

						// Calculate expected ForkId
						updateRlp, err := rlp.EncodeToBytes(upgrades)
						require.NoError(t, err, "rlp encoding failed")
						var blockNumberBytes [8]byte
						binary.BigEndian.PutUint64(blockNumberBytes[:], uint64(blockHeight))

						checkSum := crc32.ChecksumIEEE(genesisHash.Bytes())
						checkSum = crc32.Update(checkSum, crc32.IEEETable, blockNumberBytes[:])
						checkSum = crc32.Update(checkSum, crc32.IEEETable, updateRlp)

						var expectedForkId forkId
						binary.BigEndian.PutUint32(expectedForkId[:], checkSum)

						// Get ForkId from MakeForkId.
						gotForkId, err := MakeForkId(
							opera.MakeUpgradeHeight(upgrades, blockHeight),
							genesisHash)
						require.NoError(t, err, "makeForkId failed")

						require.Equal(t, expectedForkId, gotForkId,
							"fork ID does not follow the expected formula")
					},
				)
			}
		}
	}
}

func TestForkId_UpgradesProduceDifferentIds(t *testing.T) {

	proposer := map[string]bool{
		"single proposer":      true,
		"distributed proposer": false,
	}
	subsidies := map[string]bool{
		"with gas subsidies":    true,
		"without gas subsidies": false,
	}
	bundles := map[string]bool{
		"with bundles":    true,
		"without bundles": false,
	}
	priorities := map[string]bool{
		"with priorities":    true,
		"without priorities": false,
	}

	genesisHash := common.Hash{0x42}

	generated := make(map[forkId]struct{})
	for hardfork, upgrades := range opera.GetAllHardForksInOrder() {
		for proposerName, singleProposer := range proposer {
			for subsidiesName, withSubsidies := range subsidies {
				for bundlesName, withBundles := range bundles {
					for prioritiesName, withPriorities := range priorities {
						for _, height := range []idx.Block{1, 5, 10} {
							upgrades := upgrades
							upgrades.SingleProposerBlockFormation = singleProposer
							upgrades.GasSubsidies = withSubsidies
							upgrades.TransactionBundles = withBundles
							upgrades.TransactionPriorities = withPriorities

							upgradeHeight := opera.MakeUpgradeHeight(upgrades, height)
							testName := fmt.Sprintf("%s-%s-%s-%s-%s-%d", hardfork, proposerName, subsidiesName, bundlesName, prioritiesName, height)

							t.Run(testName, func(t *testing.T) {
								got, err := MakeForkId(upgradeHeight, genesisHash)
								require.NoError(t, err, "makeForkHash failed")
								_, exists := generated[got]
								require.False(t, exists, "duplicate fork ID generated for different upgrades")
								generated[got] = struct{}{}
							})
						}
					}
				}
			}
		}
	}
}

func TestForkId_ProducesDifferentIds_ForDifferentGenesis(t *testing.T) {

	sonicUpgrades := opera.MakeUpgradeHeight(opera.GetSonicUpgrades(), 1)

	tests := map[string]struct {
		genesisId common.Hash
		want      forkId
	}{
		"GenesisA": {
			genesisId: common.Hash{0x42},
			want:      forkId{0x75, 0x45, 0xd7, 0x6e},
		},
		"GenesisB": {
			genesisId: common.Hash{0x43},
			want:      forkId{0xd4, 0x7c, 0x53, 0x80},
		},
	}

	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			got, err := MakeForkId(sonicUpgrades, test.genesisId)
			require.NoError(t, err, "makeForkHash failed")
			require.Equal(t, test.want, got, "unexpected fork hash")
		})
	}
}

func TestMakeConfigFromUpgrade_Reports_AvailableSystemContracts(t *testing.T) {

	sonicHeight := idx.Block(1)
	allegroHeight := idx.Block(5)
	gasSubsidiesHeight := idx.Block(10)
	prioritiesHeight := idx.Block(15)

	tests := map[string]struct {
		upgradeHeight    opera.UpgradeHeight
		wantSysContracts contractRegistry
	}{
		"Sonic": {
			upgradeHeight: opera.UpgradeHeight{
				Upgrades: opera.GetSonicUpgrades(),
				Height:   sonicHeight,
			},
			wantSysContracts: contractRegistry{},
		},
		"Allegro": {
			upgradeHeight: opera.UpgradeHeight{
				Upgrades: opera.GetAllegroUpgrades(),
				Height:   allegroHeight,
			},
			wantSysContracts: contractRegistry{"HISTORY_STORAGE_ADDRESS": params.HistoryStorageAddress},
		},
		"GasSubsidies": {
			upgradeHeight: opera.UpgradeHeight{
				Upgrades: func() opera.Upgrades {
					return opera.Upgrades{GasSubsidies: true}
				}(),
				Height: gasSubsidiesHeight,
			},
			wantSysContracts: contractRegistry{"GAS_SUBSIDY_REGISTRY_ADDRESS": subsidiesRegistry.GetAddress()},
		},
		"Sonic+GasSubsidies": {
			upgradeHeight: opera.UpgradeHeight{
				Upgrades: func() opera.Upgrades {
					upgrades := opera.GetSonicUpgrades()
					upgrades.GasSubsidies = true
					return upgrades
				}(),
				Height: gasSubsidiesHeight,
			},
			wantSysContracts: contractRegistry{"GAS_SUBSIDY_REGISTRY_ADDRESS": subsidiesRegistry.GetAddress()},
		},
		"Allegro+GasSubsidies": {
			upgradeHeight: opera.UpgradeHeight{
				Upgrades: func() opera.Upgrades {
					upgrades := opera.GetAllegroUpgrades()
					upgrades.GasSubsidies = true
					return upgrades
				}(),
				Height: gasSubsidiesHeight,
			},
			wantSysContracts: contractRegistry{
				"HISTORY_STORAGE_ADDRESS":      params.HistoryStorageAddress,
				"GAS_SUBSIDY_REGISTRY_ADDRESS": subsidiesRegistry.GetAddress(),
			},
		},
		"TransactionPriorities": {
			upgradeHeight: opera.UpgradeHeight{
				Upgrades: opera.Upgrades{TransactionPriorities: true},
				Height:   prioritiesHeight,
			},
			wantSysContracts: contractRegistry{"TRANSACTION_PRIORITY_REGISTRY_ADDRESS": priorityRegistry.GetAddress()},
		},
		"Allegro+GasSubsidies+TransactionPriorities": {
			upgradeHeight: opera.UpgradeHeight{
				Upgrades: func() opera.Upgrades {
					upgrades := opera.GetAllegroUpgrades()
					upgrades.GasSubsidies = true
					upgrades.TransactionPriorities = true
					return upgrades
				}(),
				Height: prioritiesHeight,
			},
			wantSysContracts: contractRegistry{
				"HISTORY_STORAGE_ADDRESS":               params.HistoryStorageAddress,
				"GAS_SUBSIDY_REGISTRY_ADDRESS":          subsidiesRegistry.GetAddress(),
				"TRANSACTION_PRIORITY_REGISTRY_ADDRESS": priorityRegistry.GetAddress(),
			},
		},
	}

	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			chainId := big.NewInt(250)
			chainCfg := opera.CreateTransientEvmChainConfig(
				chainId.Uint64(),
				[]opera.UpgradeHeight{test.upgradeHeight},
				test.upgradeHeight.Height,
			)

			ctrl := gomock.NewController(t)
			backend := NewMockBackend(ctrl)
			backend.EXPECT().ChainID().Return(chainId)
			backend.EXPECT().ChainConfig(gomock.Any()).Return(chainCfg)
			backend.EXPECT().GetGenesisID().Return(common.Hash{0x42})
			backend.EXPECT().BlockByNumber(gomock.Any(), rpc.BlockNumber(int64(test.upgradeHeight.Height))).
				Return(&evmcore.EvmBlock{EvmHeader: evmcore.EvmHeader{
					Number: new(big.Int).SetUint64(uint64(test.upgradeHeight.Height)),
					Time:   inter.Timestamp(1),
				}}, nil)

			result, err := makeConfigFromUpgrade(context.Background(), backend, test.upgradeHeight)
			require.NoError(t, err, "unexpected error from makeConfigFromUpgrade")

			require.Equal(t, test.wantSysContracts, result.SystemContracts,
				"unexpected system contracts")
		})
	}
}

func TestMakeConfigFromUpgrade_ReportsErrors_WhenBlockByNumberReturnsAnError(t *testing.T) {
	ctrl := gomock.NewController(t)
	backend := NewMockBackend(ctrl)

	chainId := big.NewInt(250)
	backend.EXPECT().ChainID().Return(chainId)
	chainCfg := opera.CreateTransientEvmChainConfig(
		chainId.Uint64(),
		[]opera.UpgradeHeight{{}},
		0,
	)
	backend.EXPECT().ChainConfig(gomock.Any()).Return(chainCfg)
	backend.EXPECT().GetGenesisID().Return(common.Hash{0x42})

	backend.EXPECT().BlockByNumber(gomock.Any(), rpc.BlockNumber(int64(0))).
		Return(nil, fmt.Errorf("some error"))

	_, err := makeConfigFromUpgrade(t.Context(), backend, opera.UpgradeHeight{})
	require.ErrorContains(t, err, "could not get block")
}

func TestMakeConfigFromUpgrade_ReportsError_WhenBlockByNumberReturnsNilBlock(t *testing.T) {
	ctrl := gomock.NewController(t)
	backend := NewMockBackend(ctrl)

	chainId := big.NewInt(250)
	backend.EXPECT().ChainID().Return(chainId)
	chainCfg := opera.CreateTransientEvmChainConfig(
		chainId.Uint64(),
		[]opera.UpgradeHeight{{}},
		0,
	)
	backend.EXPECT().ChainConfig(gomock.Any()).Return(chainCfg)
	backend.EXPECT().GetGenesisID().Return(common.Hash{0x42})

	backend.EXPECT().BlockByNumber(gomock.Any(), rpc.BlockNumber(int64(0))).
		Return(nil, nil)

	_, err := makeConfigFromUpgrade(t.Context(), backend, opera.UpgradeHeight{})
	require.ErrorContains(t, err, "block 0 not found")
}

func TestMakeConfigFromUpgrade_ReportsError_WhenBlockCarriesNoNumber(t *testing.T) {
	ctrl := gomock.NewController(t)
	backend := NewMockBackend(ctrl)

	chainId := big.NewInt(250)
	backend.EXPECT().ChainID().Return(chainId)
	chainCfg := opera.CreateTransientEvmChainConfig(
		chainId.Uint64(),
		[]opera.UpgradeHeight{{}},
		0,
	)
	backend.EXPECT().ChainConfig(gomock.Any()).Return(chainCfg)
	backend.EXPECT().GetGenesisID().Return(common.Hash{0x42})

	backend.EXPECT().BlockByNumber(gomock.Any(), rpc.BlockNumber(int64(0))).
		Return(&evmcore.EvmBlock{}, nil)

	_, err := makeConfigFromUpgrade(t.Context(), backend, opera.UpgradeHeight{})
	require.ErrorContains(t, err, "block 0 carries no number")
}

func TestMakeConfigFromUpgrade_ReportsError_WhenUpgradeHeightExceedsMaxInt64(t *testing.T) {
	// rpc.BlockNumber is signed and its negative values name the block tags, so a
	// height beyond MaxInt64 must be rejected rather than wrapped into a tag.
	ctrl := gomock.NewController(t)
	backend := NewMockBackend(ctrl)

	chainId := big.NewInt(250)
	backend.EXPECT().ChainID().Return(chainId)
	chainCfg := opera.CreateTransientEvmChainConfig(
		chainId.Uint64(),
		[]opera.UpgradeHeight{{}},
		0,
	)
	backend.EXPECT().ChainConfig(gomock.Any()).Return(chainCfg)
	backend.EXPECT().GetGenesisID().Return(common.Hash{0x42})

	// No BlockByNumber call is expected: the height never reaches the backend.
	upgradeHeight := opera.UpgradeHeight{Height: idx.Block(math.MaxInt64) + 1}

	_, err := makeConfigFromUpgrade(t.Context(), backend, upgradeHeight)
	require.ErrorContains(t, err, "exceeds the largest addressable block number")
}

func TestEIP7910_Config_ReportsErrors(t *testing.T) {

	currentBlock := evmcore.EvmBlock{
		EvmHeader: evmcore.EvmHeader{
			Number: big.NewInt(5),
		},
	}

	tests := map[string]struct {
		backendSetup func(*MockBackend)
		expectedErr  string
	}{
		"fails to get current block": {
			backendSetup: func(mockBackend *MockBackend) {
				mockBackend.EXPECT().CurrentBlock().Return(nil)
			},
			expectedErr: "current block header not found",
		},
		"fails to get upgrade heights for current block": {
			backendSetup: func(mockBackend *MockBackend) {
				mockBackend.EXPECT().CurrentBlock().Return(&currentBlock)
				mockBackend.EXPECT().GetUpgradeHeights().Return(nil)
			},
			expectedErr: "no configs found",
		},
	}

	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			ctrl := gomock.NewController(t)
			backend := NewMockBackend(ctrl)

			test.backendSetup(backend)

			api := NewPublicBlockChainAPI(backend)
			_, err := api.Config(context.Background())
			require.Error(t, err)
			require.Contains(t, err.Error(), test.expectedErr)
		})
	}
}

func TestEIP7910_Config_ReturnsConfigs(t *testing.T) {

	chainId := big.NewInt(250)
	currentBlock := evmcore.EvmBlock{
		EvmHeader: evmcore.EvmHeader{
			Number: big.NewInt(5),
		},
	}

	sonicPrecompiled := contractRegistry{
		"BLAKE2F":              common.BytesToAddress([]byte{0x09}),
		"BN254_ADD":            common.BytesToAddress([]byte{0x06}),
		"BN254_MUL":            common.BytesToAddress([]byte{0x07}),
		"BN254_PAIRING":        common.BytesToAddress([]byte{0x08}),
		"ECREC":                common.BytesToAddress([]byte{0x01}),
		"ID":                   common.BytesToAddress([]byte{0x04}),
		"KZG_POINT_EVALUATION": common.BytesToAddress([]byte{0x0A}),
		"MODEXP":               common.BytesToAddress([]byte{0x05}),
		"RIPEMD160":            common.BytesToAddress([]byte{0x03}),
		"SHA256":               common.BytesToAddress([]byte{0x02}),
	}

	allegroPrecompiled := maps.Clone(sonicPrecompiled)
	allegroPrecompiled["BLS12_G1ADD"] = common.BytesToAddress([]byte{0x0B})
	allegroPrecompiled["BLS12_G1MSM"] = common.BytesToAddress([]byte{0x0C})
	allegroPrecompiled["BLS12_G2ADD"] = common.BytesToAddress([]byte{0x0D})
	allegroPrecompiled["BLS12_G2MSM"] = common.BytesToAddress([]byte{0x0E})
	allegroPrecompiled["BLS12_PAIRING_CHECK"] = common.BytesToAddress([]byte{0x0F})
	allegroPrecompiled["BLS12_MAP_FP_TO_G1"] = common.BytesToAddress([]byte{0x10})
	allegroPrecompiled["BLS12_MAP_FP2_TO_G2"] = common.BytesToAddress([]byte{0x11})

	tests := map[string]struct {
		backendSetup func(*MockBackend)
		wantConfig   configResponse
	}{
		"only current block config": {
			backendSetup: func(mockBackend *MockBackend) {
				mockBackend.EXPECT().CurrentBlock().Return(&currentBlock)
				upgradeHeights := []opera.UpgradeHeight{
					{
						Upgrades: opera.GetSonicUpgrades(),
						Height:   idx.Block(1),
					},
				}
				mockBackend.EXPECT().GetUpgradeHeights().Return(upgradeHeights)
				chainConfig := opera.CreateTransientEvmChainConfig(
					chainId.Uint64(),
					upgradeHeights,
					idx.Block(currentBlock.Number.Uint64()),
				)
				mockBackend.EXPECT().ChainConfig(gomock.Any()).Return(chainConfig)

			},
			wantConfig: func() configResponse {
				sonicId, err := MakeForkId(opera.MakeUpgradeHeight(opera.GetSonicUpgrades(), 1), common.Hash{0x42})
				require.NoError(t, err, "makeForkId failed for sonic upgrades")
				return configResponse{Current: &config{
					BlockHeight:     (*hexutil.Big)(big.NewInt(1)),
					ChainId:         (*hexutil.Big)(chainId),
					ForkId:          sonicId[:],
					Precompiles:     sonicPrecompiled,
					SystemContracts: activeSystemContracts(opera.GetSonicUpgrades()),
				},
				}
			}(),
		},
		"current and last block configs": {
			backendSetup: func(mockBackend *MockBackend) {
				mockBackend.EXPECT().CurrentBlock().Return(&currentBlock)
				upgradeHeights := []opera.UpgradeHeight{
					{
						Upgrades: opera.GetSonicUpgrades(),
						Height:   idx.Block(1),
					},
					{
						Upgrades: opera.GetAllegroUpgrades(),
						Height:   idx.Block(5),
					},
				}
				mockBackend.EXPECT().GetUpgradeHeights().Return(upgradeHeights)
				currentChainConfig := opera.CreateTransientEvmChainConfig(
					chainId.Uint64(),
					upgradeHeights,
					idx.Block(5),
				)
				mockBackend.EXPECT().ChainConfig(idx.Block(5)).Return(currentChainConfig)
				lastChainConfig := opera.CreateTransientEvmChainConfig(
					chainId.Uint64(),
					upgradeHeights,
					idx.Block(1),
				)
				mockBackend.EXPECT().ChainConfig(idx.Block(1)).Return(lastChainConfig)

			},
			wantConfig: func() configResponse {
				sonicId, err := MakeForkId(opera.MakeUpgradeHeight(opera.GetSonicUpgrades(), 1), common.Hash{0x42})
				require.NoError(t, err, "makeForkId failed for sonic upgrades")

				allegroId, err := MakeForkId(opera.MakeUpgradeHeight(opera.GetAllegroUpgrades(), 5), common.Hash{0x42})
				require.NoError(t, err, "makeForkId failed for allegro upgrades")

				return configResponse{
					Current: &config{
						BlockHeight:     (*hexutil.Big)(big.NewInt(5)),
						ChainId:         (*hexutil.Big)(chainId),
						ForkId:          allegroId[:],
						Precompiles:     allegroPrecompiled,
						SystemContracts: activeSystemContracts(opera.GetAllegroUpgrades()),
					},
					Last: &config{
						BlockHeight:     (*hexutil.Big)(big.NewInt(1)),
						ChainId:         (*hexutil.Big)(chainId),
						ForkId:          sonicId[:],
						Precompiles:     sonicPrecompiled,
						SystemContracts: activeSystemContracts(opera.GetSonicUpgrades()),
					},
				}
			}(),
		},
	}

	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			ctrl := gomock.NewController(t)
			backend := NewMockBackend(ctrl)
			backend.EXPECT().ChainID().Return(chainId).AnyTimes()
			// could be called once or twice depending on the test case.
			backend.EXPECT().GetGenesisID().Return(common.Hash{0x42}).AnyTimes()
			// The block a request resolves to is the one at the requested height, so
			// the stub echoes the number back: makeConfigFromUpgrade reads it to
			// resolve the height-gated upgrades.
			backend.EXPECT().BlockByNumber(gomock.Any(), gomock.Any()).
				DoAndReturn(func(_ context.Context, number rpc.BlockNumber) (*evmcore.EvmBlock, error) {
					return &evmcore.EvmBlock{EvmHeader: evmcore.EvmHeader{
						Number: big.NewInt(number.Int64()),
						Time:   inter.Timestamp(1),
					}}, nil
				}).AnyTimes()

			test.backendSetup(backend)

			api := NewPublicBlockChainAPI(backend)
			gotConfig, err := api.Config(context.Background())

			require.NoError(t, err)
			require.Equal(t, test.wantConfig, *gotConfig)
		})
	}
}

func TestEIP7910_Config_ResolvesTimeGatedForksWithTheBlockTime(t *testing.T) {
	// A chain config whose forks are gated on real timestamps -- a foreign chain
	// replayed through the backend, unlike Sonic's own transient config, which
	// places every time-gated fork at timestamp 0. The precompile set must follow
	// the block's time, not a zero one.
	forkTime := uint64(480)
	blockTime := forkTime + 60

	chainId := big.NewInt(250)
	upgradeHeights := []opera.UpgradeHeight{{
		Upgrades: opera.GetBrioUpgrades(),
		Height:   idx.Block(5),
	}}
	chainConfig := &params.ChainConfig{
		ChainID:        chainId,
		HomesteadBlock: big.NewInt(0),
		EIP150Block:    big.NewInt(0),
		EIP155Block:    big.NewInt(0),
		EIP158Block:    big.NewInt(0),
		ByzantiumBlock: big.NewInt(0),
		BerlinBlock:    big.NewInt(0),
		LondonBlock:    big.NewInt(0),
		ShanghaiTime:   &forkTime,
		CancunTime:     &forkTime,
		PragueTime:     &forkTime,
		OsakaTime:      &forkTime,
	}

	ctrl := gomock.NewController(t)
	backend := NewMockBackend(ctrl)
	backend.EXPECT().ChainID().Return(chainId).AnyTimes()
	backend.EXPECT().GetGenesisID().Return(common.Hash{0x42}).AnyTimes()
	backend.EXPECT().CurrentBlock().Return(&evmcore.EvmBlock{
		EvmHeader: evmcore.EvmHeader{Number: big.NewInt(5)},
	})
	backend.EXPECT().GetUpgradeHeights().Return(upgradeHeights)
	backend.EXPECT().ChainConfig(gomock.Any()).Return(chainConfig)
	backend.EXPECT().BlockByNumber(gomock.Any(), gomock.Any()).Return(&evmcore.EvmBlock{
		EvmHeader: evmcore.EvmHeader{
			Number: big.NewInt(5),
			Time:   inter.FromUnix(int64(blockTime)),
		},
	}, nil)

	gotConfig, err := NewPublicBlockChainAPI(backend).Config(context.Background())
	require.NoError(t, err)
	require.Equal(t, blockTime, gotConfig.Current.ActivationTime)

	// The Osaka precompile set: everything Prague has, plus P256VERIFY.
	require.Contains(t, gotConfig.Current.Precompiles, "P256VERIFY")
	require.Contains(t, gotConfig.Current.Precompiles, "KZG_POINT_EVALUATION")
	require.Contains(t, gotConfig.Current.Precompiles, "BLS12_PAIRING_CHECK")
}

func TestEIP7910_Config_ReportsAZeroBlobScheduleAndTheActivatingBlockHeight(t *testing.T) {
	// EIP-7910 requires blobSchedule to be an object, and Sonic has no blobs, so
	// the schedule reports zero capacity. blockHeight is Sonic's extension beyond
	// the specification: it names the block whose transaction activated the
	// upgrade, which is how Sonic activates one.
	chainId := big.NewInt(250)
	upgradeHeights := []opera.UpgradeHeight{{
		Upgrades: opera.GetSonicUpgrades(),
		Height:   idx.Block(5),
	}}

	ctrl := gomock.NewController(t)
	backend := NewMockBackend(ctrl)
	backend.EXPECT().ChainID().Return(chainId)
	backend.EXPECT().GetGenesisID().Return(common.Hash{0x42})
	backend.EXPECT().CurrentBlock().Return(&evmcore.EvmBlock{
		EvmHeader: evmcore.EvmHeader{Number: big.NewInt(5)},
	})
	backend.EXPECT().GetUpgradeHeights().Return(upgradeHeights)
	backend.EXPECT().ChainConfig(gomock.Any()).Return(opera.CreateTransientEvmChainConfig(
		chainId.Uint64(), upgradeHeights, idx.Block(5),
	))
	backend.EXPECT().BlockByNumber(gomock.Any(), gomock.Any()).Return(&evmcore.EvmBlock{
		EvmHeader: evmcore.EvmHeader{
			Number: big.NewInt(5),
			Time:   inter.FromUnix(540),
		},
	}, nil)

	gotConfig, err := NewPublicBlockChainAPI(backend).Config(context.Background())
	require.NoError(t, err)
	require.Equal(t, params.BlobConfig{}, gotConfig.Current.BlobSchedule)

	encoded, err := json.Marshal(gotConfig)
	require.NoError(t, err)

	var decoded map[string]map[string]any
	require.NoError(t, json.Unmarshal(encoded, &decoded))
	require.Equal(t, "0x5", decoded["current"]["blockHeight"])
	require.Equal(t, map[string]any{
		"target":                float64(0),
		"max":                   float64(0),
		"baseFeeUpdateFraction": float64(0),
	}, decoded["current"]["blobSchedule"])
}
