// Code generated by "stringer -type=AuthChoice -trimprefix=Auth"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AuthSelf-0]
	_ = x[AuthOther-1]
	_ = x[AuthWrongChainID-2]
}

const _AuthChoice_name = "SelfOtherWrongChainID"

var _AuthChoice_index = [...]uint8{0, 4, 9, 21}

func (i AuthChoice) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AuthChoice_index)-1 {
		return "AuthChoice(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AuthChoice_name[_AuthChoice_index[idx]:_AuthChoice_index[idx+1]]
}
