// Code generated by "stringer -type=NonceChoice -trimprefix=Nonce"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NonceCorrect-0]
	_ = x[NonceTooLow-1]
	_ = x[NonceGap-2]
	_ = x[NonceMax-3]
}

const _NonceChoice_name = "CorrectTooLowGapMax"

var _NonceChoice_index = [...]uint8{0, 7, 13, 16, 19}

func (i NonceChoice) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_NonceChoice_index)-1 {
		return "NonceChoice(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NonceChoice_name[_NonceChoice_index[idx]:_NonceChoice_index[idx+1]]
}
