// Code generated by "stringer -type=Outcome -trimprefix=Outcome"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OutcomeEventRejected-0]
	_ = x[OutcomeDropped-1]
	_ = x[OutcomeExecuted-2]
}

const _Outcome_name = "EventRejectedDroppedExecuted"

var _Outcome_index = [...]uint8{0, 13, 20, 28}

func (i Outcome) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Outcome_index)-1 {
		return "Outcome(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Outcome_name[_Outcome_index[idx]:_Outcome_index[idx+1]]
}
