// Code generated by "stringer -type=SigningChoice -trimprefix=Sign"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SignCorrect-0]
	_ = x[SignWrongChainID-1]
	_ = x[SignUnfundedKey-2]
	_ = x[SignZeroR-3]
	_ = x[SignZeroS-4]
	_ = x[SignForeign-5]
}

const _SigningChoice_name = "CorrectWrongChainIDUnfundedKeyZeroRZeroSForeign"

var _SigningChoice_index = [...]uint8{0, 7, 19, 30, 35, 40, 47}

func (i SigningChoice) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SigningChoice_index)-1 {
		return "SigningChoice(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SigningChoice_name[_SigningChoice_index[idx]:_SigningChoice_index[idx+1]]
}
