// Code generated by "stringer -type=ToChoice -trimprefix=To"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ToSelf-0]
	_ = x[ToOther-1]
	_ = x[ToCreate-2]
	_ = x[ToPrecompile-3]
	_ = x[ToContract-4]
}

const _ToChoice_name = "SelfOtherCreatePrecompileContract"

var _ToChoice_index = [...]uint8{0, 4, 9, 15, 25, 33}

func (i ToChoice) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ToChoice_index)-1 {
		return "ToChoice(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ToChoice_name[_ToChoice_index[idx]:_ToChoice_index[idx+1]]
}
