// Code generated by "stringer -type=MutationKind -trimprefix=Mutate"; DO NOT EDIT.

package contracts

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MutateNone-0]
	_ = x[MutateSelector-1]
	_ = x[MutateFlip-2]
	_ = x[MutateTruncate-3]
	_ = x[MutateExtend-4]
	_ = x[MutateDropArgs-5]
}

const _MutationKind_name = "NoneSelectorFlipTruncateExtendDropArgs"

var _MutationKind_index = [...]uint8{0, 4, 12, 16, 24, 30, 38}

func (i MutationKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MutationKind_index)-1 {
		return "MutationKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MutationKind_name[_MutationKind_index[idx]:_MutationKind_index[idx+1]]
}
