name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # example: v2.0.12 (rc intentionally excluded)

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Golang dependency
        uses: actions/setup-go@v3
        with:
          go-version: "1.24"

      - name: Build
        run: make

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          draft: true # create release as a draft
          artifacts: "./build/sonicd,./build/sonictool"
